export interface Guest {
  name: string;
  phone: string;
  totalStays: number;
  totalRevenue: number;
  lastStay: string;
  nextArrival: string;
  nightlyRate: number;
  nights: number;
  roomType: string;
  bookingLeadDays: number;
  guestSegment: "impulse" | "planner" | "loyalist" | "new";
  enrichmentScore: number;
  occupation: string | null;
  company: string | null;
  ageEstimate: number | null;
  linkedinUrl: string | null;
  socialPresence: "high" | "moderate" | "low" | "none";
  vipScore: number;
  tags: string[];
}

export const guests: Guest[] = [
  {
    name: "Harrington, Claire",
    phone: "914.552.3847",
    totalStays: 6,
    totalRevenue: 8940,
    lastStay: "2025-11-15",
    nextArrival: "2026-04-11",
    nightlyRate: 289,
    nights: 3,
    roomType: "ROYAL",
    bookingLeadDays: 45,
    guestSegment: "loyalist",
    enrichmentScore: 92,
    occupation: "Managing Director",
    company: "Blackstone Real Estate",
    ageEstimate: 44,
    linkedinUrl: "https://linkedin.com/in/claireharrington",
    socialPresence: "high",
    vipScore: 94,
    tags: ["repeat", "high-value", "young-professional"],
  },
  {
    name: "Westbrook, Marcus",
    phone: "917.384.6120",
    totalStays: 5,
    totalRevenue: 7250,
    lastStay: "2025-12-28",
    nextArrival: "2026-04-08",
    nightlyRate: 349,
    nights: 2,
    roomType: "IMPST",
    bookingLeadDays: 3,
    guestSegment: "loyalist",
    enrichmentScore: 88,
    occupation: "VP of Operations",
    company: "Marriott Select",
    ageEstimate: 51,
    linkedinUrl: "https://linkedin.com/in/marcuswestbrook",
    socialPresence: "high",
    vipScore: 91,
    tags: ["repeat", "high-value", "hospitality-insider"],
  },
  {
    name: "Chen, Lily",
    phone: "646.891.2043",
    totalStays: 4,
    totalRevenue: 5680,
    lastStay: "2025-10-22",
    nextArrival: "2026-04-18",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 62,
    guestSegment: "loyalist",
    enrichmentScore: 95,
    occupation: "Creative Director",
    company: "Wieden+Kennedy",
    ageEstimate: 36,
    linkedinUrl: "https://linkedin.com/in/lilychen-creative",
    socialPresence: "high",
    vipScore: 87,
    tags: ["repeat", "young-professional", "influencer-potential"],
  },
  {
    name: "Kowalski, Brian",
    phone: "516.447.8832",
    totalStays: 4,
    totalRevenue: 6120,
    lastStay: "2025-09-14",
    nextArrival: "2026-04-25",
    nightlyRate: 319,
    nights: 3,
    roomType: "ROYAL",
    bookingLeadDays: 78,
    guestSegment: "loyalist",
    enrichmentScore: 71,
    occupation: "Orthopedic Surgeon",
    company: "NYU Langone",
    ageEstimate: 48,
    linkedinUrl: "https://linkedin.com/in/briankowalski-md",
    socialPresence: "moderate",
    vipScore: 85,
    tags: ["repeat", "high-value", "medical-professional"],
  },
  {
    name: "Alvarez, Sofia",
    phone: "212.903.4471",
    totalStays: 3,
    totalRevenue: 4350,
    lastStay: "2025-08-30",
    nextArrival: "2026-04-12",
    nightlyRate: 289,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 34,
    guestSegment: "loyalist",
    enrichmentScore: 84,
    occupation: "Portfolio Manager",
    company: "Goldman Sachs",
    ageEstimate: 39,
    linkedinUrl: "https://linkedin.com/in/sofiaalvarez-gs",
    socialPresence: "moderate",
    vipScore: 82,
    tags: ["repeat", "young-professional", "finance"],
  },
  {
    name: "Brennan, Patrick",
    phone: "845.221.6609",
    totalStays: 3,
    totalRevenue: 3870,
    lastStay: "2025-11-02",
    nextArrival: "2026-05-02",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 91,
    guestSegment: "planner",
    enrichmentScore: 67,
    occupation: "High School Principal",
    company: "Kingston City Schools",
    ageEstimate: 55,
    linkedinUrl: "https://linkedin.com/in/patbrennan-edu",
    socialPresence: "low",
    vipScore: 68,
    tags: ["repeat", "local", "educator"],
  },
  {
    name: "Tanaka, Yuki",
    phone: "347.882.1155",
    totalStays: 3,
    totalRevenue: 5190,
    lastStay: "2025-07-19",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 91,
    occupation: "Head of Product",
    company: "Peloton",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/yukitanaka",
    socialPresence: "high",
    vipScore: 80,
    tags: ["repeat", "young-professional", "tech"],
  },
  {
    name: "Morrison, Beth",
    phone: "631.445.9023",
    totalStays: 3,
    totalRevenue: 4080,
    lastStay: "2025-12-20",
    nextArrival: "2026-05-16",
    nightlyRate: 289,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 105,
    guestSegment: "planner",
    enrichmentScore: 58,
    occupation: "Retired — Teacher",
    company: null,
    ageEstimate: 67,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 65,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Dominguez, Rafael",
    phone: "718.330.7782",
    totalStays: 2,
    totalRevenue: 3240,
    lastStay: "2025-06-08",
    nextArrival: "2026-04-10",
    nightlyRate: 319,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 18,
    guestSegment: "planner",
    enrichmentScore: 79,
    occupation: "Executive Chef",
    company: "Jean-Georges Restaurants",
    ageEstimate: 41,
    linkedinUrl: "https://linkedin.com/in/rafaeldominguez-chef",
    socialPresence: "moderate",
    vipScore: 72,
    tags: ["repeat", "f-and-b-industry"],
  },
  {
    name: "Sullivan, Kate",
    phone: "203.661.4490",
    totalStays: 2,
    totalRevenue: 2780,
    lastStay: "2025-10-05",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 55,
    guestSegment: "planner",
    enrichmentScore: 86,
    occupation: "Partner",
    company: "Deloitte Consulting",
    ageEstimate: 46,
    linkedinUrl: "https://linkedin.com/in/katesullivan-deloitte",
    socialPresence: "moderate",
    vipScore: 71,
    tags: ["repeat", "high-value", "consulting"],
  },
  {
    name: "Patel, Aarav",
    phone: "862.209.3374",
    totalStays: 2,
    totalRevenue: 2460,
    lastStay: "2025-05-18",
    nextArrival: "2026-04-26",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 4,
    guestSegment: "impulse",
    enrichmentScore: 73,
    occupation: "Software Engineer",
    company: "Stripe",
    ageEstimate: 29,
    linkedinUrl: "https://linkedin.com/in/aaravpatel-dev",
    socialPresence: "moderate",
    vipScore: 58,
    tags: ["repeat", "young-professional", "tech"],
  },
  {
    name: "O'Brien, Declan",
    phone: "914.773.2218",
    totalStays: 2,
    totalRevenue: 3560,
    lastStay: "2025-09-28",
    nextArrival: "2026-05-03",
    nightlyRate: 289,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 67,
    guestSegment: "planner",
    enrichmentScore: 44,
    occupation: "Contractor",
    company: "O'Brien & Sons Construction",
    ageEstimate: 52,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 62,
    tags: ["repeat", "local-business"],
  },
  {
    name: "Nakamura, Emi",
    phone: "917.550.8891",
    totalStays: 2,
    totalRevenue: 4180,
    lastStay: "2025-11-30",
    nextArrival: "2026-04-12",
    nightlyRate: 349,
    nights: 2,
    roomType: "IMPST",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 97,
    occupation: "Fashion Director",
    company: "Condé Nast",
    ageEstimate: 38,
    linkedinUrl: "https://linkedin.com/in/eminakamura",
    socialPresence: "high",
    vipScore: 78,
    tags: ["repeat", "young-professional", "media", "influencer-potential"],
  },
  {
    name: "Wheeler, James",
    phone: "845.339.1102",
    totalStays: 2,
    totalRevenue: 1980,
    lastStay: "2025-04-12",
    nextArrival: "2026-06-14",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 112,
    guestSegment: "planner",
    enrichmentScore: 31,
    occupation: null,
    company: null,
    ageEstimate: 71,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 38,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Fitzgerald, Nora",
    phone: "508.229.6647",
    totalStays: 2,
    totalRevenue: 2890,
    lastStay: "2025-08-17",
    nextArrival: "2026-04-15",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 43,
    guestSegment: "planner",
    enrichmentScore: 82,
    occupation: "Veterinarian",
    company: "Catskill Animal Hospital",
    ageEstimate: 44,
    linkedinUrl: "https://linkedin.com/in/norafitzgerald-dvm",
    socialPresence: "moderate",
    vipScore: 64,
    tags: ["repeat", "local"],
  },
  {
    name: "Kim, Daniel",
    phone: "646.201.9938",
    totalStays: 1,
    totalRevenue: 1756,
    lastStay: "2025-12-31",
    nextArrival: "2026-04-08",
    nightlyRate: 439,
    nights: 4,
    roomType: "IMPST",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 93,
    occupation: "Founding Partner",
    company: "Benchmark Capital",
    ageEstimate: 42,
    linkedinUrl: "https://linkedin.com/in/danielkim-vc",
    socialPresence: "high",
    vipScore: 76,
    tags: ["new", "high-value", "finance", "young-professional"],
  },
  {
    name: "Rossi, Valentina",
    phone: "212.774.3301",
    totalStays: 1,
    totalRevenue: 1347,
    lastStay: "2025-11-22",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 3,
    roomType: "STRMS",
    bookingLeadDays: 5,
    guestSegment: "impulse",
    enrichmentScore: 89,
    occupation: "Interior Designer",
    company: "Studio Rossi",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/valentinarossi-design",
    socialPresence: "high",
    vipScore: 69,
    tags: ["new", "young-professional", "design"],
  },
  {
    name: "Thompson, Greg",
    phone: "973.882.4456",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-10-10",
    nextArrival: "2026-04-19",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 38,
    guestSegment: "planner",
    enrichmentScore: 76,
    occupation: "Financial Advisor",
    company: "Edward Jones",
    ageEstimate: 53,
    linkedinUrl: "https://linkedin.com/in/gregthompson-ej",
    socialPresence: "moderate",
    vipScore: 45,
    tags: ["new", "finance"],
  },
  {
    name: "Liu, Jasmine",
    phone: "347.991.5528",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-09-05",
    nextArrival: "2026-04-25",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 94,
    occupation: "Marketing Manager",
    company: "Glossier",
    ageEstimate: 31,
    linkedinUrl: "https://linkedin.com/in/jasmineliu-mktg",
    socialPresence: "high",
    vipScore: 55,
    tags: ["new", "young-professional", "marketing"],
  },
  {
    name: "Murphy, Sean",
    phone: "845.626.7734",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-07-04",
    nextArrival: "2026-05-23",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 88,
    guestSegment: "planner",
    enrichmentScore: 42,
    occupation: "Park Ranger",
    company: "NYS DEC",
    ageEstimate: 47,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 32,
    tags: ["new", "government"],
  },
  {
    name: "Bakshi, Priya",
    phone: "201.330.9981",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-06-20",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 14,
    guestSegment: "planner",
    enrichmentScore: 88,
    occupation: "Radiologist",
    company: "Mount Sinai",
    ageEstimate: 40,
    linkedinUrl: "https://linkedin.com/in/priyabakshi-md",
    socialPresence: "moderate",
    vipScore: 52,
    tags: ["new", "medical-professional"],
  },
  {
    name: "Carlson, Erik",
    phone: "518.774.2209",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-12-14",
    nextArrival: "2026-06-07",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 120,
    guestSegment: "planner",
    enrichmentScore: 22,
    occupation: null,
    company: null,
    ageEstimate: 68,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 21,
    tags: ["new", "retiree"],
  },
  {
    name: "Williams, Jasper",
    phone: "929.415.6673",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-08-09",
    nextArrival: "2026-04-12",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 96,
    occupation: "CEO",
    company: "Willow & Stone Hospitality",
    ageEstimate: 45,
    linkedinUrl: "https://linkedin.com/in/jasperwilliams-ceo",
    socialPresence: "high",
    vipScore: 73,
    tags: ["new", "high-value", "hospitality-insider"],
  },
  {
    name: "Romano, Gina",
    phone: "914.882.3310",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-05-25",
    nextArrival: "2026-04-18",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 29,
    guestSegment: "planner",
    enrichmentScore: 65,
    occupation: "Real Estate Agent",
    company: "Compass RE",
    ageEstimate: 37,
    linkedinUrl: "https://linkedin.com/in/ginaromano-re",
    socialPresence: "moderate",
    vipScore: 44,
    tags: ["new", "young-professional", "real-estate"],
  },
  {
    name: "Banks, Terrence",
    phone: "718.550.1127",
    totalStays: 1,
    totalRevenue: 996,
    lastStay: "2025-11-08",
    nextArrival: "2026-05-10",
    nightlyRate: 249,
    nights: 4,
    roomType: "DEL2Q",
    bookingLeadDays: 7,
    guestSegment: "impulse",
    enrichmentScore: 81,
    occupation: "Photographer",
    company: "Freelance",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/terrencebanks-photo",
    socialPresence: "high",
    vipScore: 48,
    tags: ["new", "young-professional", "creative"],
  },
  {
    name: "Duffy, Maeve",
    phone: "203.447.8895",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-10-19",
    nextArrival: "2026-04-26",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 51,
    guestSegment: "planner",
    enrichmentScore: 70,
    occupation: "Attorney",
    company: "Davis Polk & Wardwell",
    ageEstimate: 43,
    linkedinUrl: "https://linkedin.com/in/maeveduffy-law",
    socialPresence: "moderate",
    vipScore: 50,
    tags: ["new", "legal"],
  },
  {
    name: "Ostrowski, Jan",
    phone: "631.228.4401",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-30",
    nextArrival: "2026-07-04",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 95,
    guestSegment: "planner",
    enrichmentScore: 18,
    occupation: null,
    company: null,
    ageEstimate: 72,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 18,
    tags: ["new", "retiree"],
  },
  {
    name: "Rivera, Marco",
    phone: "917.663.8847",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-09-20",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 4,
    guestSegment: "impulse",
    enrichmentScore: 85,
    occupation: "Brand Strategist",
    company: "Nike",
    ageEstimate: 36,
    linkedinUrl: "https://linkedin.com/in/marcorivera-brand",
    socialPresence: "high",
    vipScore: 58,
    tags: ["new", "young-professional", "marketing"],
  },
  {
    name: "Jensen, Karen",
    phone: "845.991.2234",
    totalStays: 2,
    totalRevenue: 2380,
    lastStay: "2025-07-27",
    nextArrival: "2026-05-30",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 74,
    guestSegment: "planner",
    enrichmentScore: 53,
    occupation: "School Nurse",
    company: "Saugerties Central Schools",
    ageEstimate: 50,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 55,
    tags: ["repeat", "local"],
  },
  {
    name: "Park, Joon",
    phone: "646.338.7721",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-12-07",
    nextArrival: "2026-04-09",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 91,
    occupation: "Architect",
    company: "SHoP Architects",
    ageEstimate: 38,
    linkedinUrl: "https://linkedin.com/in/joonpark-arch",
    socialPresence: "high",
    vipScore: 62,
    tags: ["new", "young-professional", "design"],
  },
  {
    name: "McAllister, Fiona",
    phone: "508.773.4456",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-06-14",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 22,
    guestSegment: "planner",
    enrichmentScore: 77,
    occupation: "Physical Therapist",
    company: "Hudson Valley PT",
    ageEstimate: 42,
    linkedinUrl: "https://linkedin.com/in/fionamcallister-pt",
    socialPresence: "moderate",
    vipScore: 41,
    tags: ["new", "healthcare"],
  },
  {
    name: "Foster, Derek",
    phone: "973.115.9938",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-08-23",
    nextArrival: "2026-05-17",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 60,
    guestSegment: "planner",
    enrichmentScore: 39,
    occupation: "Electrician",
    company: "IBEW Local 363",
    ageEstimate: 56,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 29,
    tags: ["new", "trades"],
  },
  {
    name: "Adebayo, Tunde",
    phone: "347.228.5501",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-10-31",
    nextArrival: "2026-04-11",
    nightlyRate: 349,
    nights: 4,
    roomType: "IMPST",
    bookingLeadDays: 8,
    guestSegment: "impulse",
    enrichmentScore: 90,
    occupation: "Investment Analyst",
    company: "KKR",
    ageEstimate: 32,
    linkedinUrl: "https://linkedin.com/in/tundeadebayo-kkr",
    socialPresence: "moderate",
    vipScore: 63,
    tags: ["new", "young-professional", "finance", "high-value"],
  },
  {
    name: "Chambers, Lori",
    phone: "914.447.3320",
    totalStays: 2,
    totalRevenue: 2180,
    lastStay: "2025-09-13",
    nextArrival: "2026-06-21",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 98,
    guestSegment: "planner",
    enrichmentScore: 35,
    occupation: "Retired — Accountant",
    company: null,
    ageEstimate: 64,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 42,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Volkov, Dmitri",
    phone: "718.993.7748",
    totalStays: 1,
    totalRevenue: 747,
    lastStay: "2025-11-16",
    nextArrival: "2026-04-25",
    nightlyRate: 249,
    nights: 3,
    roomType: "DEL2Q",
    bookingLeadDays: 11,
    guestSegment: "impulse",
    enrichmentScore: 72,
    occupation: "Data Scientist",
    company: "Two Sigma",
    ageEstimate: 30,
    linkedinUrl: "https://linkedin.com/in/dmitrivolkov-ds",
    socialPresence: "moderate",
    vipScore: 46,
    tags: ["new", "young-professional", "tech"],
  },
  {
    name: "Santiago, Isabel",
    phone: "212.881.6632",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-07-11",
    nextArrival: "2026-04-18",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 35,
    guestSegment: "planner",
    enrichmentScore: 83,
    occupation: "Event Planner",
    company: "PCMA Events",
    ageEstimate: 37,
    linkedinUrl: "https://linkedin.com/in/isabelsantiago-events",
    socialPresence: "high",
    vipScore: 49,
    tags: ["new", "young-professional", "events"],
  },
  {
    name: "Crawford, Bill",
    phone: "845.667.1109",
    totalStays: 3,
    totalRevenue: 3570,
    lastStay: "2025-12-26",
    nextArrival: "2026-04-08",
    nightlyRate: 219,
    nights: 3,
    roomType: "REG2Q",
    bookingLeadDays: 85,
    guestSegment: "loyalist",
    enrichmentScore: 28,
    occupation: "Retired — FDNY",
    company: null,
    ageEstimate: 66,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 60,
    tags: ["repeat", "retiree", "local"],
  },
  {
    name: "Nguyen, Tiffany",
    phone: "929.774.2283",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-05-03",
    nextArrival: "2026-04-12",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 6,
    guestSegment: "impulse",
    enrichmentScore: 87,
    occupation: "UX Researcher",
    company: "Airbnb",
    ageEstimate: 28,
    linkedinUrl: "https://linkedin.com/in/tiffanynguyen-ux",
    socialPresence: "high",
    vipScore: 43,
    tags: ["new", "young-professional", "tech"],
  },
  {
    name: "Gallagher, Tom",
    phone: "516.882.4478",
    totalStays: 4,
    totalRevenue: 5960,
    lastStay: "2025-10-18",
    nextArrival: "2026-04-09",
    nightlyRate: 289,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 52,
    guestSegment: "loyalist",
    enrichmentScore: 61,
    occupation: "General Contractor",
    company: "Gallagher Builders",
    ageEstimate: 58,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 79,
    tags: ["repeat", "high-value", "local-business"],
  },
  {
    name: "Becker, Anna",
    phone: "201.559.8814",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-08-02",
    nextArrival: "2026-05-09",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 92,
    occupation: "Wellness Coach",
    company: "Mindful Movement Co",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/annabecker-wellness",
    socialPresence: "high",
    vipScore: 54,
    tags: ["new", "young-professional", "wellness"],
  },
  {
    name: "Hart, Douglas",
    phone: "845.334.0091",
    totalStays: 2,
    totalRevenue: 1960,
    lastStay: "2025-06-29",
    nextArrival: "2026-07-11",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 105,
    guestSegment: "planner",
    enrichmentScore: 15,
    occupation: null,
    company: null,
    ageEstimate: 74,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 33,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Lee, Sarah",
    phone: "646.502.3319",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-12-05",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 95,
    occupation: "VP of Marketing",
    company: "Warby Parker",
    ageEstimate: 37,
    linkedinUrl: "https://linkedin.com/in/sarahlee-wp",
    socialPresence: "high",
    vipScore: 66,
    tags: ["new", "young-professional", "marketing", "high-value"],
  },
  {
    name: "Moretti, Giancarlo",
    phone: "914.220.5587",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-09-27",
    nextArrival: "2026-04-26",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 40,
    guestSegment: "planner",
    enrichmentScore: 74,
    occupation: "Restaurant Owner",
    company: "Trattoria Moretti",
    ageEstimate: 49,
    linkedinUrl: null,
    socialPresence: "moderate",
    vipScore: 47,
    tags: ["new", "f-and-b-industry", "local-business"],
  },
  {
    name: "Shaw, Rebecca",
    phone: "203.991.7743",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-04-19",
    nextArrival: "2026-05-31",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 72,
    guestSegment: "planner",
    enrichmentScore: 60,
    occupation: "Librarian",
    company: "Woodstock Library",
    ageEstimate: 45,
    linkedinUrl: "https://linkedin.com/in/rebeccashaw-lib",
    socialPresence: "low",
    vipScore: 30,
    tags: ["new", "local"],
  },
  {
    name: "Ahmed, Farid",
    phone: "347.661.8804",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-10-25",
    nextArrival: "2026-04-11",
    nightlyRate: 349,
    nights: 4,
    roomType: "LUXRM",
    bookingLeadDays: 5,
    guestSegment: "impulse",
    enrichmentScore: 86,
    occupation: "Cardiologist",
    company: "Columbia Presbyterian",
    ageEstimate: 46,
    linkedinUrl: "https://linkedin.com/in/fariahmed-md",
    socialPresence: "moderate",
    vipScore: 61,
    tags: ["new", "medical-professional", "high-value"],
  },
  {
    name: "Collins, Megan",
    phone: "917.443.2276",
    totalStays: 2,
    totalRevenue: 2780,
    lastStay: "2025-11-09",
    nextArrival: "2026-04-15",
    nightlyRate: 289,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 31,
    guestSegment: "planner",
    enrichmentScore: 80,
    occupation: "Yoga Instructor",
    company: "CorePower Yoga",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/megancollins-yoga",
    socialPresence: "high",
    vipScore: 59,
    tags: ["repeat", "young-professional", "wellness"],
  },
  {
    name: "Reeves, Craig",
    phone: "516.774.0023",
    totalStays: 1,
    totalRevenue: 438,
    lastStay: "2025-07-26",
    nextArrival: "2026-06-28",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 92,
    guestSegment: "planner",
    enrichmentScore: 25,
    occupation: null,
    company: null,
    ageEstimate: 62,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 22,
    tags: ["new", "retiree"],
  },
  {
    name: "Blackwell, Simone",
    phone: "718.229.4458",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-12-21",
    nextArrival: "2026-04-09",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 93,
    occupation: "Documentary Filmmaker",
    company: "Blackwell Films",
    ageEstimate: 39,
    linkedinUrl: "https://linkedin.com/in/simoneblackwell-film",
    socialPresence: "high",
    vipScore: 57,
    tags: ["new", "young-professional", "creative", "influencer-potential"],
  },
  {
    name: "Howell, Kenneth",
    phone: "845.558.3347",
    totalStays: 3,
    totalRevenue: 3270,
    lastStay: "2025-08-16",
    nextArrival: "2026-05-24",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 80,
    guestSegment: "loyalist",
    enrichmentScore: 47,
    occupation: "Plumber",
    company: "Howell Plumbing",
    ageEstimate: 54,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 61,
    tags: ["repeat", "local-business", "trades"],
  },
  {
    name: "Warren, Lisa",
    phone: "212.663.9912",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-10-04",
    nextArrival: "2026-04-18",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 9,
    guestSegment: "impulse",
    enrichmentScore: 88,
    occupation: "Art Director",
    company: "The New York Times",
    ageEstimate: 41,
    linkedinUrl: "https://linkedin.com/in/lisawarren-nyt",
    socialPresence: "high",
    vipScore: 56,
    tags: ["new", "young-professional", "media"],
  },
  {
    name: "DiMaggio, Tony",
    phone: "914.330.7765",
    totalStays: 2,
    totalRevenue: 2460,
    lastStay: "2025-09-06",
    nextArrival: "2026-04-25",
    nightlyRate: 249,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 45,
    guestSegment: "planner",
    enrichmentScore: 55,
    occupation: "Auto Dealer",
    company: "DiMaggio Motors",
    ageEstimate: 57,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 53,
    tags: ["repeat", "local-business"],
  },
  {
    name: "Yoon, Grace",
    phone: "646.889.1104",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-06-07",
    nextArrival: "2026-04-12",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 91,
    occupation: "Venture Capital Associate",
    company: "Andreessen Horowitz",
    ageEstimate: 29,
    linkedinUrl: "https://linkedin.com/in/graceyoon-a16z",
    socialPresence: "high",
    vipScore: 51,
    tags: ["new", "young-professional", "finance"],
  },
  {
    name: "Campbell, Robert",
    phone: "845.774.8890",
    totalStays: 5,
    totalRevenue: 6850,
    lastStay: "2025-12-13",
    nextArrival: "2026-04-08",
    nightlyRate: 269,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 65,
    guestSegment: "loyalist",
    enrichmentScore: 40,
    occupation: "Retired — IBM",
    company: null,
    ageEstimate: 69,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 82,
    tags: ["repeat", "high-value", "retiree", "local"],
  },
  {
    name: "Torres, Diana",
    phone: "929.337.5568",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-05-10",
    nextArrival: "2026-04-19",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 26,
    guestSegment: "planner",
    enrichmentScore: 79,
    occupation: "Nonprofit Director",
    company: "Catskill Center",
    ageEstimate: 43,
    linkedinUrl: "https://linkedin.com/in/dianatorres-nonprofit",
    socialPresence: "moderate",
    vipScore: 42,
    tags: ["new", "local", "community-leader"],
  },
  {
    name: "Katz, Jason",
    phone: "516.229.6631",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-08-30",
    nextArrival: "2026-05-16",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 58,
    guestSegment: "planner",
    enrichmentScore: 68,
    occupation: "Dentist",
    company: "Katz Family Dental",
    ageEstimate: 50,
    linkedinUrl: "https://linkedin.com/in/jasonkatz-dds",
    socialPresence: "low",
    vipScore: 36,
    tags: ["new", "medical-professional"],
  },
  {
    name: "Novak, Peter",
    phone: "862.441.3309",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-11-28",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 4,
    guestSegment: "impulse",
    enrichmentScore: 84,
    occupation: "Film Producer",
    company: "A24",
    ageEstimate: 40,
    linkedinUrl: "https://linkedin.com/in/peternovak-a24",
    socialPresence: "high",
    vipScore: 59,
    tags: ["new", "young-professional", "entertainment"],
  },
  {
    name: "Mitchell, Sandra",
    phone: "203.882.5547",
    totalStays: 2,
    totalRevenue: 2380,
    lastStay: "2025-10-11",
    nextArrival: "2026-06-06",
    nightlyRate: 249,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 83,
    guestSegment: "planner",
    enrichmentScore: 48,
    occupation: "Retired — Nurse",
    company: null,
    ageEstimate: 63,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 46,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Ruiz, Alejandro",
    phone: "347.773.9921",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-07-19",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 90,
    occupation: "Music Producer",
    company: "Electric Feel Studios",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/alejandroruiz-music",
    socialPresence: "high",
    vipScore: 55,
    tags: ["new", "young-professional", "creative"],
  },
  {
    name: "Donahue, Patrick",
    phone: "914.559.0012",
    totalStays: 3,
    totalRevenue: 4170,
    lastStay: "2025-12-06",
    nextArrival: "2026-04-08",
    nightlyRate: 289,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 47,
    guestSegment: "loyalist",
    enrichmentScore: 62,
    occupation: "Insurance Broker",
    company: "Donahue & Associates",
    ageEstimate: 52,
    linkedinUrl: "https://linkedin.com/in/patdonahue-insurance",
    socialPresence: "moderate",
    vipScore: 74,
    tags: ["repeat", "high-value", "local-business"],
  },
  {
    name: "Hayashi, Kenji",
    phone: "646.118.7743",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-09-13",
    nextArrival: "2026-04-26",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 17,
    guestSegment: "planner",
    enrichmentScore: 82,
    occupation: "Mechanical Engineer",
    company: "Tesla",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/kenjihayashi-eng",
    socialPresence: "moderate",
    vipScore: 44,
    tags: ["new", "young-professional", "tech"],
  },
  {
    name: "Powers, Linda",
    phone: "518.993.4421",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-05",
    nextArrival: "2026-07-18",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 110,
    guestSegment: "planner",
    enrichmentScore: 20,
    occupation: null,
    company: null,
    ageEstimate: 70,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 19,
    tags: ["new", "retiree"],
  },
  {
    name: "Gibson, Marcus",
    phone: "917.229.8836",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-11-01",
    nextArrival: "2026-04-12",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 5,
    guestSegment: "impulse",
    enrichmentScore: 87,
    occupation: "Sports Agent",
    company: "CAA Sports",
    ageEstimate: 42,
    linkedinUrl: "https://linkedin.com/in/marcusgibson-caa",
    socialPresence: "high",
    vipScore: 60,
    tags: ["new", "high-value", "entertainment"],
  },
  {
    name: "Quinn, Eileen",
    phone: "845.441.2278",
    totalStays: 2,
    totalRevenue: 2180,
    lastStay: "2025-08-24",
    nextArrival: "2026-05-09",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 70,
    guestSegment: "planner",
    enrichmentScore: 38,
    occupation: "Retired — Teacher",
    company: null,
    ageEstimate: 65,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 44,
    tags: ["repeat", "retiree", "local"],
  },
  {
    name: "Okafor, Chidi",
    phone: "347.554.1198",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-12-19",
    nextArrival: "2026-04-09",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 94,
    occupation: "Startup Founder",
    company: "NomadStay",
    ageEstimate: 31,
    linkedinUrl: "https://linkedin.com/in/chidiokafor-founder",
    socialPresence: "high",
    vipScore: 58,
    tags: ["new", "young-professional", "tech", "hospitality-insider"],
  },
  {
    name: "Larson, Steve",
    phone: "516.663.0054",
    totalStays: 4,
    totalRevenue: 5480,
    lastStay: "2025-10-26",
    nextArrival: "2026-04-25",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 56,
    guestSegment: "loyalist",
    enrichmentScore: 51,
    occupation: "CPA",
    company: "Larson & Miller CPAs",
    ageEstimate: 55,
    linkedinUrl: "https://linkedin.com/in/stevelarson-cpa",
    socialPresence: "low",
    vipScore: 76,
    tags: ["repeat", "high-value", "local-business"],
  },
  {
    name: "Vasquez, Carolina",
    phone: "212.338.9907",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-06-21",
    nextArrival: "2026-04-18",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 33,
    guestSegment: "planner",
    enrichmentScore: 81,
    occupation: "HR Director",
    company: "PepsiCo",
    ageEstimate: 44,
    linkedinUrl: "https://linkedin.com/in/carolinavasquez-hr",
    socialPresence: "moderate",
    vipScore: 47,
    tags: ["new", "corporate"],
  },
  {
    name: "Pike, George",
    phone: "845.882.7712",
    totalStays: 2,
    totalRevenue: 1960,
    lastStay: "2025-07-05",
    nextArrival: "2026-06-27",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 100,
    guestSegment: "planner",
    enrichmentScore: 12,
    occupation: null,
    company: null,
    ageEstimate: 76,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 31,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Cho, Mina",
    phone: "929.661.4432",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-10-03",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 7,
    guestSegment: "impulse",
    enrichmentScore: 89,
    occupation: "Industrial Designer",
    company: "Frog Design",
    ageEstimate: 36,
    linkedinUrl: "https://linkedin.com/in/minacho-design",
    socialPresence: "high",
    vipScore: 54,
    tags: ["new", "young-professional", "design"],
  },
  {
    name: "Barrett, Kathleen",
    phone: "203.774.1165",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-05-17",
    nextArrival: "2026-05-22",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 64,
    guestSegment: "planner",
    enrichmentScore: 56,
    occupation: "Real Estate Appraiser",
    company: "Barrett Valuation Group",
    ageEstimate: 48,
    linkedinUrl: "https://linkedin.com/in/kathleenbarrett-appraisal",
    socialPresence: "low",
    vipScore: 34,
    tags: ["new", "real-estate"],
  },
  {
    name: "Hoffman, Rachel",
    phone: "718.443.5521",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-11-14",
    nextArrival: "2026-04-12",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 92,
    occupation: "Travel Writer",
    company: "Condé Nast Traveler",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/rachelhoffman-travel",
    socialPresence: "high",
    vipScore: 64,
    tags: ["new", "young-professional", "media", "influencer-potential"],
  },
  {
    name: "Greco, Vincent",
    phone: "914.991.3348",
    totalStays: 3,
    totalRevenue: 3870,
    lastStay: "2025-12-28",
    nextArrival: "2026-04-08",
    nightlyRate: 249,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 42,
    guestSegment: "loyalist",
    enrichmentScore: 58,
    occupation: "Pharmacist",
    company: "CVS Health",
    ageEstimate: 51,
    linkedinUrl: "https://linkedin.com/in/vincentgreco-pharmd",
    socialPresence: "low",
    vipScore: 70,
    tags: ["repeat", "medical-professional"],
  },
  {
    name: "Sato, Hiro",
    phone: "646.772.8819",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-08-09",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 19,
    guestSegment: "planner",
    enrichmentScore: 78,
    occupation: "Robotics Engineer",
    company: "Boston Dynamics",
    ageEstimate: 32,
    linkedinUrl: "https://linkedin.com/in/hirosato-robotics",
    socialPresence: "moderate",
    vipScore: 43,
    tags: ["new", "young-professional", "tech"],
  },
  {
    name: "Kelly, Maureen",
    phone: "845.228.4467",
    totalStays: 2,
    totalRevenue: 2380,
    lastStay: "2025-09-20",
    nextArrival: "2026-05-03",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 68,
    guestSegment: "planner",
    enrichmentScore: 43,
    occupation: "School Secretary",
    company: "Phoenicia Elementary",
    ageEstimate: 53,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 48,
    tags: ["repeat", "local"],
  },
  {
    name: "Bennett, Tyler",
    phone: "917.338.6657",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-10-17",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 86,
    occupation: "Craft Brewer",
    company: "Suarez Family Brewery",
    ageEstimate: 37,
    linkedinUrl: "https://linkedin.com/in/tylerbennett-brew",
    socialPresence: "moderate",
    vipScore: 52,
    tags: ["new", "young-professional", "f-and-b-industry", "local"],
  },
  {
    name: "Price, Dorothy",
    phone: "518.662.3345",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-26",
    nextArrival: "2026-08-01",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 118,
    guestSegment: "planner",
    enrichmentScore: 14,
    occupation: null,
    company: null,
    ageEstimate: 73,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 16,
    tags: ["new", "retiree"],
  },
  {
    name: "Abrams, Leah",
    phone: "347.882.0093",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-11-22",
    nextArrival: "2026-04-11",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 12,
    guestSegment: "impulse",
    enrichmentScore: 83,
    occupation: "Brand Consultant",
    company: "Independent",
    ageEstimate: 38,
    linkedinUrl: "https://linkedin.com/in/leahabrams-brand",
    socialPresence: "high",
    vipScore: 49,
    tags: ["new", "young-professional", "marketing"],
  },
  {
    name: "Petrov, Nikolai",
    phone: "718.991.4438",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-07-12",
    nextArrival: "2026-05-30",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 55,
    guestSegment: "planner",
    enrichmentScore: 66,
    occupation: "Civil Engineer",
    company: "AECOM",
    ageEstimate: 46,
    linkedinUrl: "https://linkedin.com/in/nikolaipetrov-eng",
    socialPresence: "moderate",
    vipScore: 37,
    tags: ["new", "engineering"],
  },
  {
    name: "Walsh, Bridget",
    phone: "914.663.2219",
    totalStays: 2,
    totalRevenue: 2780,
    lastStay: "2025-12-14",
    nextArrival: "2026-04-15",
    nightlyRate: 289,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 38,
    guestSegment: "planner",
    enrichmentScore: 75,
    occupation: "Physical Therapist",
    company: "HSS",
    ageEstimate: 41,
    linkedinUrl: "https://linkedin.com/in/bridgetwalsh-pt",
    socialPresence: "moderate",
    vipScore: 58,
    tags: ["repeat", "healthcare"],
  },
  {
    name: "Monroe, David",
    phone: "845.447.8801",
    totalStays: 1,
    totalRevenue: 438,
    lastStay: "2025-06-28",
    nextArrival: "2026-06-13",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 88,
    guestSegment: "planner",
    enrichmentScore: 30,
    occupation: "Retired — Engineer",
    company: null,
    ageEstimate: 67,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 25,
    tags: ["new", "retiree"],
  },
  {
    name: "Singh, Arjun",
    phone: "929.223.5541",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-10-31",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 4,
    roomType: "LUXRM",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 93,
    occupation: "Private Equity VP",
    company: "Apollo Global",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/arjunsingh-pe",
    socialPresence: "moderate",
    vipScore: 67,
    tags: ["new", "young-professional", "finance", "high-value"],
  },
  {
    name: "Porter, Janet",
    phone: "203.559.1178",
    totalStays: 3,
    totalRevenue: 3570,
    lastStay: "2025-09-07",
    nextArrival: "2026-05-17",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 75,
    guestSegment: "loyalist",
    enrichmentScore: 45,
    occupation: "Retired — Librarian",
    company: null,
    ageEstimate: 64,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 62,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Ortega, Mateo",
    phone: "646.774.3327",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-12-06",
    nextArrival: "2026-04-12",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 90,
    occupation: "DJ / Music Artist",
    company: "Independent",
    ageEstimate: 28,
    linkedinUrl: "https://linkedin.com/in/mateortega-music",
    socialPresence: "high",
    vipScore: 50,
    tags: ["new", "young-professional", "creative", "influencer-potential"],
  },
  {
    name: "Fleming, Scott",
    phone: "516.882.9934",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-08-16",
    nextArrival: "2026-04-26",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 41,
    guestSegment: "planner",
    enrichmentScore: 71,
    occupation: "Sales Director",
    company: "Salesforce",
    ageEstimate: 47,
    linkedinUrl: "https://linkedin.com/in/scottfleming-sf",
    socialPresence: "moderate",
    vipScore: 45,
    tags: ["new", "corporate", "tech"],
  },
  {
    name: "Bergman, Annika",
    phone: "201.441.7762",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-05-24",
    nextArrival: "2026-04-18",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 28,
    guestSegment: "planner",
    enrichmentScore: 76,
    occupation: "Environmental Scientist",
    company: "EPA Region 2",
    ageEstimate: 40,
    linkedinUrl: "https://linkedin.com/in/annikabergman-env",
    socialPresence: "moderate",
    vipScore: 40,
    tags: ["new", "government", "science"],
  },
  {
    name: "Hawkins, Darnell",
    phone: "347.993.1182",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-11-08",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 6,
    guestSegment: "impulse",
    enrichmentScore: 85,
    occupation: "Personal Trainer",
    company: "Equinox",
    ageEstimate: 31,
    linkedinUrl: "https://linkedin.com/in/darnellhawkins-fit",
    socialPresence: "high",
    vipScore: 51,
    tags: ["new", "young-professional", "wellness"],
  },
  {
    name: "Stone, Margaret",
    phone: "845.334.5568",
    totalStays: 4,
    totalRevenue: 5160,
    lastStay: "2025-12-21",
    nextArrival: "2026-04-08",
    nightlyRate: 249,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 50,
    guestSegment: "loyalist",
    enrichmentScore: 52,
    occupation: "Gallery Owner",
    company: "Stone Gallery Woodstock",
    ageEstimate: 59,
    linkedinUrl: null,
    socialPresence: "moderate",
    vipScore: 77,
    tags: ["repeat", "high-value", "local-business", "art"],
  },
  {
    name: "Young, Andre",
    phone: "917.110.4489",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-07-05",
    nextArrival: "2026-05-09",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 48,
    guestSegment: "planner",
    enrichmentScore: 69,
    occupation: "Teacher",
    company: "Bronx Academy of Letters",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/andreyoung-edu",
    socialPresence: "low",
    vipScore: 33,
    tags: ["new", "educator"],
  },
  {
    name: "Magnusson, Erik",
    phone: "718.557.2213",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-10-18",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 88,
    occupation: "Landscape Architect",
    company: "MVVA",
    ageEstimate: 43,
    linkedinUrl: "https://linkedin.com/in/erikmagnusson-la",
    socialPresence: "moderate",
    vipScore: 53,
    tags: ["new", "design", "outdoor-enthusiast"],
  },
  {
    name: "Cooper, Denise",
    phone: "914.228.3341",
    totalStays: 2,
    totalRevenue: 2180,
    lastStay: "2025-09-14",
    nextArrival: "2026-05-31",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 82,
    guestSegment: "planner",
    enrichmentScore: 33,
    occupation: "Retired — Postal Worker",
    company: null,
    ageEstimate: 66,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 40,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Keane, Ryan",
    phone: "646.339.7756",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-12-01",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 4,
    guestSegment: "impulse",
    enrichmentScore: 91,
    occupation: "Podcast Host",
    company: "The Adventure Pod",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/ryankeane-pod",
    socialPresence: "high",
    vipScore: 56,
    tags: [
      "new",
      "young-professional",
      "media",
      "influencer-potential",
      "outdoor-enthusiast",
    ],
  },
  {
    name: "Lang, Christine",
    phone: "203.882.0056",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-06-13",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 36,
    guestSegment: "planner",
    enrichmentScore: 74,
    occupation: "Nutritionist",
    company: "Whole Health Nutrition",
    ageEstimate: 39,
    linkedinUrl: "https://linkedin.com/in/christinelang-rd",
    socialPresence: "moderate",
    vipScore: 41,
    tags: ["new", "wellness"],
  },
  {
    name: "Marshall, Wayne",
    phone: "845.991.6678",
    totalStays: 3,
    totalRevenue: 3870,
    lastStay: "2025-11-23",
    nextArrival: "2026-04-25",
    nightlyRate: 289,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 59,
    guestSegment: "loyalist",
    enrichmentScore: 49,
    occupation: "HVAC Technician",
    company: "Marshall Heating & Cooling",
    ageEstimate: 54,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 68,
    tags: ["repeat", "local-business", "trades"],
  },
  {
    name: "Andersen, Mia",
    phone: "929.447.8821",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-08-02",
    nextArrival: "2026-04-12",
    nightlyRate: 299,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 8,
    guestSegment: "impulse",
    enrichmentScore: 85,
    occupation: "Sustainability Consultant",
    company: "McKinsey",
    ageEstimate: 36,
    linkedinUrl: "https://linkedin.com/in/miaandersen-mckinsey",
    socialPresence: "high",
    vipScore: 50,
    tags: ["new", "young-professional", "consulting"],
  },
  {
    name: "Schultz, Gary",
    phone: "516.330.1147",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-12",
    nextArrival: "2026-07-25",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 108,
    guestSegment: "planner",
    enrichmentScore: 17,
    occupation: null,
    company: null,
    ageEstimate: 71,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 17,
    tags: ["new", "retiree"],
  },
  {
    name: "Dubois, Camille",
    phone: "212.661.3398",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-10-05",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 4,
    roomType: "IMPST",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 96,
    occupation: "Fragrance Designer",
    company: "Le Labo",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/camilledubois-lelabo",
    socialPresence: "high",
    vipScore: 65,
    tags: ["new", "young-professional", "luxury", "creative"],
  },
  {
    name: "Mooney, Jack",
    phone: "845.557.4429",
    totalStays: 5,
    totalRevenue: 7450,
    lastStay: "2025-12-27",
    nextArrival: "2026-04-08",
    nightlyRate: 289,
    nights: 3,
    roomType: "ROYAL",
    bookingLeadDays: 40,
    guestSegment: "loyalist",
    enrichmentScore: 55,
    occupation: "Fly Fishing Guide",
    company: "Catskill Fly Fishing",
    ageEstimate: 48,
    linkedinUrl: null,
    socialPresence: "moderate",
    vipScore: 84,
    tags: ["repeat", "high-value", "local-business", "outdoor-enthusiast"],
  },
  {
    name: "Franklin, Amy",
    phone: "917.774.5563",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-05-31",
    nextArrival: "2026-04-18",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 44,
    guestSegment: "planner",
    enrichmentScore: 72,
    occupation: "Social Worker",
    company: "NYC Health + Hospitals",
    ageEstimate: 42,
    linkedinUrl: "https://linkedin.com/in/amyfranklin-lcsw",
    socialPresence: "low",
    vipScore: 35,
    tags: ["new", "healthcare"],
  },
  {
    name: "Eriksson, Lars",
    phone: "646.993.2247",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-11-15",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 87,
    occupation: "Ski Instructor",
    company: "Windham Mountain",
    ageEstimate: 30,
    linkedinUrl: "https://linkedin.com/in/larseriksson-ski",
    socialPresence: "high",
    vipScore: 48,
    tags: ["new", "young-professional", "outdoor-enthusiast", "local"],
  },
  {
    name: "Palmer, Joan",
    phone: "203.441.8834",
    totalStays: 2,
    totalRevenue: 2380,
    lastStay: "2025-10-19",
    nextArrival: "2026-06-20",
    nightlyRate: 249,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 90,
    guestSegment: "planner",
    enrichmentScore: 41,
    occupation: "Retired — Principal",
    company: null,
    ageEstimate: 68,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 45,
    tags: ["repeat", "retiree", "educator"],
  },
  {
    name: "Cross, Damien",
    phone: "347.118.6694",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-07-26",
    nextArrival: "2026-04-12",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 5,
    guestSegment: "impulse",
    enrichmentScore: 84,
    occupation: "Graphic Designer",
    company: "Pentagram",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/damiencross-design",
    socialPresence: "high",
    vipScore: 52,
    tags: ["new", "young-professional", "design"],
  },
  {
    name: "Thornton, Richard",
    phone: "914.663.0025",
    totalStays: 1,
    totalRevenue: 438,
    lastStay: "2025-09-06",
    nextArrival: "2026-05-16",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 65,
    guestSegment: "planner",
    enrichmentScore: 37,
    occupation: "Retired — Banker",
    company: null,
    ageEstimate: 69,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 26,
    tags: ["new", "retiree"],
  },
  {
    name: "Wu, Kevin",
    phone: "929.882.3316",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-12-13",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 10,
    guestSegment: "impulse",
    enrichmentScore: 90,
    occupation: "Software Architect",
    company: "Datadog",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/kevinwu-datadog",
    socialPresence: "moderate",
    vipScore: 46,
    tags: ["new", "young-professional", "tech"],
  },
  {
    name: "McGuire, Colleen",
    phone: "845.774.2298",
    totalStays: 3,
    totalRevenue: 3570,
    lastStay: "2025-11-02",
    nextArrival: "2026-04-08",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 53,
    guestSegment: "loyalist",
    enrichmentScore: 59,
    occupation: "Bed & Breakfast Owner",
    company: "The Catskill Lodge",
    ageEstimate: 56,
    linkedinUrl: null,
    socialPresence: "moderate",
    vipScore: 66,
    tags: ["repeat", "hospitality-insider", "local-business"],
  },
  {
    name: "Pham, Linh",
    phone: "646.447.9928",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-08-23",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 93,
    occupation: "Food Blogger",
    company: "Taste of New York",
    ageEstimate: 30,
    linkedinUrl: "https://linkedin.com/in/linhpham-food",
    socialPresence: "high",
    vipScore: 53,
    tags: [
      "new",
      "young-professional",
      "f-and-b-industry",
      "influencer-potential",
    ],
  },
  {
    name: "Gregory, Donald",
    phone: "518.339.0012",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-19",
    nextArrival: "2026-08-08",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 115,
    guestSegment: "planner",
    enrichmentScore: 11,
    occupation: null,
    company: null,
    ageEstimate: 75,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 14,
    tags: ["new", "retiree"],
  },
  {
    name: "Ellis, Shannon",
    phone: "201.882.7743",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-10-11",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 4,
    guestSegment: "impulse",
    enrichmentScore: 88,
    occupation: "Pilates Instructor",
    company: "Club Pilates",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/shannonellis-pilates",
    socialPresence: "high",
    vipScore: 50,
    tags: ["new", "young-professional", "wellness"],
  },
  {
    name: "Moran, Patrick",
    phone: "914.221.5589",
    totalStays: 2,
    totalRevenue: 2460,
    lastStay: "2025-09-28",
    nextArrival: "2026-04-26",
    nightlyRate: 249,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 47,
    guestSegment: "planner",
    enrichmentScore: 64,
    occupation: "Fire Chief",
    company: "Saugerties FD",
    ageEstimate: 52,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 55,
    tags: ["repeat", "local", "government"],
  },
  {
    name: "Tancredi, Maria",
    phone: "212.559.8812",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-06-07",
    nextArrival: "2026-04-18",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 30,
    guestSegment: "planner",
    enrichmentScore: 77,
    occupation: "Fashion Buyer",
    company: "Saks Fifth Avenue",
    ageEstimate: 39,
    linkedinUrl: "https://linkedin.com/in/mariatancredi-saks",
    socialPresence: "moderate",
    vipScore: 47,
    tags: ["new", "young-professional", "fashion"],
  },
  {
    name: "Gray, Harold",
    phone: "845.663.1156",
    totalStays: 4,
    totalRevenue: 5480,
    lastStay: "2025-12-20",
    nextArrival: "2026-04-09",
    nightlyRate: 269,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 57,
    guestSegment: "loyalist",
    enrichmentScore: 44,
    occupation: "Retired — NYPD",
    company: null,
    ageEstimate: 63,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 73,
    tags: ["repeat", "high-value", "retiree"],
  },
  {
    name: "Stein, Rebecca",
    phone: "929.774.5541",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-07-19",
    nextArrival: "2026-05-03",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 42,
    guestSegment: "planner",
    enrichmentScore: 73,
    occupation: "Occupational Therapist",
    company: "Burke Rehabilitation",
    ageEstimate: 44,
    linkedinUrl: "https://linkedin.com/in/rebeccastein-ot",
    socialPresence: "low",
    vipScore: 36,
    tags: ["new", "healthcare"],
  },
  {
    name: "Santos, Miguel",
    phone: "718.338.0091",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-11-29",
    nextArrival: "2026-04-11",
    nightlyRate: 349,
    nights: 4,
    roomType: "IMPST",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 86,
    occupation: "Sommelier",
    company: "Eleven Madison Park",
    ageEstimate: 37,
    linkedinUrl: "https://linkedin.com/in/miguelsantos-wine",
    socialPresence: "moderate",
    vipScore: 57,
    tags: ["new", "young-professional", "f-and-b-industry"],
  },
  {
    name: "Ingram, Wendy",
    phone: "203.993.4456",
    totalStays: 1,
    totalRevenue: 438,
    lastStay: "2025-05-10",
    nextArrival: "2026-06-06",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 78,
    guestSegment: "planner",
    enrichmentScore: 29,
    occupation: null,
    company: null,
    ageEstimate: 62,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 23,
    tags: ["new", "retiree"],
  },
  {
    name: "Rosen, Daniel",
    phone: "646.220.8837",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-10-04",
    nextArrival: "2026-04-12",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 94,
    occupation: "Hedge Fund Analyst",
    company: "Citadel",
    ageEstimate: 32,
    linkedinUrl: "https://linkedin.com/in/danielrosen-citadel",
    socialPresence: "moderate",
    vipScore: 60,
    tags: ["new", "young-professional", "finance", "high-value"],
  },
  {
    name: "Phillips, Carol",
    phone: "845.447.2234",
    totalStays: 2,
    totalRevenue: 2180,
    lastStay: "2025-08-30",
    nextArrival: "2026-05-24",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 85,
    guestSegment: "planner",
    enrichmentScore: 36,
    occupation: "Retired — Secretary",
    company: null,
    ageEstimate: 67,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 41,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Bhatt, Vikram",
    phone: "347.661.3315",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-12-08",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 5,
    guestSegment: "impulse",
    enrichmentScore: 89,
    occupation: "Product Manager",
    company: "Google",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/vikrambhatt-pm",
    socialPresence: "high",
    vipScore: 55,
    tags: ["new", "young-professional", "tech"],
  },
  {
    name: "Leonard, Sheila",
    phone: "914.882.6678",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-06-21",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 33,
    guestSegment: "planner",
    enrichmentScore: 63,
    occupation: "Paralegal",
    company: "White & Case",
    ageEstimate: 43,
    linkedinUrl: "https://linkedin.com/in/sheilaleonard-legal",
    socialPresence: "low",
    vipScore: 38,
    tags: ["new", "legal"],
  },
  {
    name: "Burke, Sean",
    phone: "516.993.4409",
    totalStays: 3,
    totalRevenue: 4170,
    lastStay: "2025-11-16",
    nextArrival: "2026-04-25",
    nightlyRate: 289,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 46,
    guestSegment: "loyalist",
    enrichmentScore: 57,
    occupation: "Landscape Designer",
    company: "Burke Landscapes",
    ageEstimate: 50,
    linkedinUrl: "https://linkedin.com/in/seanburke-landscape",
    socialPresence: "moderate",
    vipScore: 71,
    tags: ["repeat", "local-business", "outdoor-enthusiast"],
  },
  {
    name: "Castillo, Elena",
    phone: "212.447.2205",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-08-09",
    nextArrival: "2026-04-11",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 15,
    guestSegment: "planner",
    enrichmentScore: 80,
    occupation: "Publicist",
    company: "Sunshine Sachs",
    ageEstimate: 36,
    linkedinUrl: "https://linkedin.com/in/elenacastillo-pr",
    socialPresence: "high",
    vipScore: 48,
    tags: ["new", "young-professional", "media"],
  },
  {
    name: "Newton, Henry",
    phone: "845.228.7741",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-05",
    nextArrival: "2026-07-04",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 102,
    guestSegment: "planner",
    enrichmentScore: 19,
    occupation: null,
    company: null,
    ageEstimate: 72,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 20,
    tags: ["new", "retiree"],
  },
  {
    name: "Chang, Wendy",
    phone: "929.553.1168",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-10-25",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 6,
    guestSegment: "impulse",
    enrichmentScore: 91,
    occupation: "Venture Partner",
    company: "Sequoia Capital",
    ageEstimate: 40,
    linkedinUrl: "https://linkedin.com/in/wendychang-sequoia",
    socialPresence: "high",
    vipScore: 62,
    tags: ["new", "high-value", "finance"],
  },
  {
    name: "Doyle, Kevin",
    phone: "914.559.3312",
    totalStays: 2,
    totalRevenue: 2780,
    lastStay: "2025-12-06",
    nextArrival: "2026-04-15",
    nightlyRate: 289,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 39,
    guestSegment: "planner",
    enrichmentScore: 66,
    occupation: "Physical Education Teacher",
    company: "Kingston High School",
    ageEstimate: 45,
    linkedinUrl: "https://linkedin.com/in/kevindoyle-pe",
    socialPresence: "low",
    vipScore: 54,
    tags: ["repeat", "educator", "local"],
  },
  {
    name: "Lindqvist, Astrid",
    phone: "646.881.0094",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-07-11",
    nextArrival: "2026-04-12",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 95,
    occupation: "Interior Stylist",
    company: "Elle Decor",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/astridlindqvist-style",
    socialPresence: "high",
    vipScore: 56,
    tags: [
      "new",
      "young-professional",
      "design",
      "media",
      "influencer-potential",
    ],
  },
  {
    name: "Russo, Anthony",
    phone: "845.662.8809",
    totalStays: 6,
    totalRevenue: 8340,
    lastStay: "2025-12-28",
    nextArrival: "2026-04-08",
    nightlyRate: 269,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 48,
    guestSegment: "loyalist",
    enrichmentScore: 42,
    occupation: "Auto Mechanic",
    company: "Russo's Auto Shop",
    ageEstimate: 57,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 88,
    tags: ["repeat", "high-value", "local-business", "trades"],
  },
  {
    name: "Segal, Nina",
    phone: "212.993.5547",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-09-13",
    nextArrival: "2026-04-18",
    nightlyRate: 269,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 25,
    guestSegment: "planner",
    enrichmentScore: 82,
    occupation: "Clinical Psychologist",
    company: "Private Practice",
    ageEstimate: 47,
    linkedinUrl: "https://linkedin.com/in/ninasegal-psyd",
    socialPresence: "moderate",
    vipScore: 42,
    tags: ["new", "medical-professional"],
  },
  {
    name: "Patterson, Earl",
    phone: "518.441.2267",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-26",
    nextArrival: "2026-08-15",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 125,
    guestSegment: "planner",
    enrichmentScore: 13,
    occupation: null,
    company: null,
    ageEstimate: 74,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 15,
    tags: ["new", "retiree"],
  },
  {
    name: "Yamamoto, Saki",
    phone: "347.774.8836",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-11-01",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 4,
    roomType: "IMPST",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 92,
    occupation: "Ceramicist",
    company: "Studio Saki",
    ageEstimate: 36,
    linkedinUrl: "https://linkedin.com/in/sakiyamamoto-ceramics",
    socialPresence: "high",
    vipScore: 58,
    tags: ["new", "young-professional", "creative", "art"],
  },
  {
    name: "Nolan, Brendan",
    phone: "914.773.0028",
    totalStays: 2,
    totalRevenue: 2460,
    lastStay: "2025-10-18",
    nextArrival: "2026-05-10",
    nightlyRate: 249,
    nights: 2,
    roomType: "LUXRM",
    bookingLeadDays: 55,
    guestSegment: "planner",
    enrichmentScore: 60,
    occupation: "Carpenter",
    company: "Nolan Woodworks",
    ageEstimate: 48,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 52,
    tags: ["repeat", "local-business", "trades"],
  },
  {
    name: "Reed, Angela",
    phone: "917.441.3378",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-06-28",
    nextArrival: "2026-04-18",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 22,
    guestSegment: "planner",
    enrichmentScore: 78,
    occupation: "Museum Curator",
    company: "Dia Beacon",
    ageEstimate: 44,
    linkedinUrl: "https://linkedin.com/in/angelareed-dia",
    socialPresence: "moderate",
    vipScore: 46,
    tags: ["new", "art", "cultural"],
  },
  {
    name: "Beck, Jonathan",
    phone: "646.335.9914",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-12-19",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 90,
    occupation: "Real Estate Developer",
    company: "Beck Development Group",
    ageEstimate: 45,
    linkedinUrl: "https://linkedin.com/in/jonathanbeck-re",
    socialPresence: "moderate",
    vipScore: 61,
    tags: ["new", "real-estate", "high-value"],
  },
  {
    name: "Garza, Lucia",
    phone: "718.883.4421",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-08-16",
    nextArrival: "2026-05-02",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 50,
    guestSegment: "planner",
    enrichmentScore: 71,
    occupation: "Social Media Manager",
    company: "Ogilvy",
    ageEstimate: 30,
    linkedinUrl: "https://linkedin.com/in/luciagarza-social",
    socialPresence: "high",
    vipScore: 39,
    tags: ["new", "young-professional", "marketing"],
  },
  {
    name: "Fitzgerald, Owen",
    phone: "845.559.7712",
    totalStays: 2,
    totalRevenue: 2180,
    lastStay: "2025-09-21",
    nextArrival: "2026-06-13",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 80,
    guestSegment: "planner",
    enrichmentScore: 34,
    occupation: "Retired — Teacher",
    company: null,
    ageEstimate: 66,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 42,
    tags: ["repeat", "retiree", "local"],
  },
  {
    name: "Park, Eunji",
    phone: "929.228.3305",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-10-31",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 7,
    guestSegment: "impulse",
    enrichmentScore: 87,
    occupation: "Pastry Chef",
    company: "Dominique Ansel Bakery",
    ageEstimate: 32,
    linkedinUrl: "https://linkedin.com/in/eunjipark-pastry",
    socialPresence: "moderate",
    vipScore: 51,
    tags: ["new", "young-professional", "f-and-b-industry"],
  },
  {
    name: "Hudson, Frank",
    phone: "516.774.1189",
    totalStays: 1,
    totalRevenue: 438,
    lastStay: "2025-05-17",
    nextArrival: "2026-07-11",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 95,
    guestSegment: "planner",
    enrichmentScore: 23,
    occupation: null,
    company: null,
    ageEstimate: 70,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 20,
    tags: ["new", "retiree"],
  },
  {
    name: "Mason, Olivia",
    phone: "212.882.7765",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-11-08",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 14,
    guestSegment: "impulse",
    enrichmentScore: 83,
    occupation: "Sommelier",
    company: "Gramercy Tavern",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/oliviamason-wine",
    socialPresence: "moderate",
    vipScore: 44,
    tags: ["new", "young-professional", "f-and-b-industry"],
  },
  {
    name: "Brady, Collin",
    phone: "845.993.0056",
    totalStays: 4,
    totalRevenue: 5960,
    lastStay: "2025-12-14",
    nextArrival: "2026-04-08",
    nightlyRate: 289,
    nights: 3,
    roomType: "ROYAL",
    bookingLeadDays: 44,
    guestSegment: "loyalist",
    enrichmentScore: 54,
    occupation: "Electrician",
    company: "Brady Electric",
    ageEstimate: 53,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 78,
    tags: ["repeat", "high-value", "local-business", "trades"],
  },
  {
    name: "Klein, Maya",
    phone: "929.661.2209",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-07-05",
    nextArrival: "2026-04-12",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 3,
    guestSegment: "impulse",
    enrichmentScore: 91,
    occupation: "UX Designer",
    company: "Figma",
    ageEstimate: 29,
    linkedinUrl: "https://linkedin.com/in/mayaklein-ux",
    socialPresence: "high",
    vipScore: 50,
    tags: ["new", "young-professional", "tech", "design"],
  },
  {
    name: "Hampton, Bruce",
    phone: "914.330.4412",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-09-27",
    nextArrival: "2026-05-17",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 62,
    guestSegment: "planner",
    enrichmentScore: 46,
    occupation: "Retired — Mechanic",
    company: null,
    ageEstimate: 65,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 28,
    tags: ["new", "retiree", "trades"],
  },
  {
    name: "Takahashi, Ren",
    phone: "646.554.7743",
    totalStays: 1,
    totalRevenue: 1396,
    lastStay: "2025-10-17",
    nextArrival: "2026-04-09",
    nightlyRate: 349,
    nights: 4,
    roomType: "IMPST",
    bookingLeadDays: 4,
    guestSegment: "impulse",
    enrichmentScore: 93,
    occupation: "Creative Technologist",
    company: "R/GA",
    ageEstimate: 33,
    linkedinUrl: "https://linkedin.com/in/rentakahashi-rga",
    socialPresence: "high",
    vipScore: 57,
    tags: ["new", "young-professional", "tech", "creative"],
  },
  {
    name: "Griffin, Maureen",
    phone: "845.441.5567",
    totalStays: 3,
    totalRevenue: 3270,
    lastStay: "2025-11-30",
    nextArrival: "2026-05-03",
    nightlyRate: 219,
    nights: 2,
    roomType: "REG2Q",
    bookingLeadDays: 72,
    guestSegment: "loyalist",
    enrichmentScore: 40,
    occupation: "Retired — Bank Teller",
    company: null,
    ageEstimate: 64,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 58,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Harris, Jerome",
    phone: "347.993.4438",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-06-14",
    nextArrival: "2026-04-18",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 20,
    guestSegment: "planner",
    enrichmentScore: 75,
    occupation: "High School Basketball Coach",
    company: "Mount Vernon HS",
    ageEstimate: 46,
    linkedinUrl: "https://linkedin.com/in/jeromeharris-coach",
    socialPresence: "moderate",
    vipScore: 40,
    tags: ["new", "educator", "sports"],
  },
  {
    name: "Weaver, Patty",
    phone: "203.662.8845",
    totalStays: 1,
    totalRevenue: 498,
    lastStay: "2025-08-02",
    nextArrival: "2026-05-30",
    nightlyRate: 249,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 68,
    guestSegment: "planner",
    enrichmentScore: 50,
    occupation: "Florist",
    company: "Catskill Mountain Florals",
    ageEstimate: 49,
    linkedinUrl: null,
    socialPresence: "moderate",
    vipScore: 34,
    tags: ["new", "local-business"],
  },
  {
    name: "Zimmerman, Max",
    phone: "917.773.1102",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-12-26",
    nextArrival: "2026-04-10",
    nightlyRate: 349,
    nights: 3,
    roomType: "LUXRM",
    bookingLeadDays: 2,
    guestSegment: "impulse",
    enrichmentScore: 88,
    occupation: "Outdoor Guide",
    company: "REI Adventures",
    ageEstimate: 31,
    linkedinUrl: "https://linkedin.com/in/maxzimmerman-adventure",
    socialPresence: "high",
    vipScore: 52,
    tags: ["new", "young-professional", "outdoor-enthusiast"],
  },
  {
    name: "Carpenter, Diane",
    phone: "845.228.0034",
    totalStays: 2,
    totalRevenue: 2460,
    lastStay: "2025-10-05",
    nextArrival: "2026-06-07",
    nightlyRate: 249,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 77,
    guestSegment: "planner",
    enrichmentScore: 47,
    occupation: "Retired — Dental Hygienist",
    company: null,
    ageEstimate: 63,
    linkedinUrl: null,
    socialPresence: "low",
    vipScore: 48,
    tags: ["repeat", "retiree"],
  },
  {
    name: "Min, David",
    phone: "646.991.8824",
    totalStays: 1,
    totalRevenue: 898,
    lastStay: "2025-09-06",
    nextArrival: "2026-04-11",
    nightlyRate: 449,
    nights: 2,
    roomType: "STRMS",
    bookingLeadDays: 1,
    guestSegment: "impulse",
    enrichmentScore: 92,
    occupation: "Brand Director",
    company: "Patagonia",
    ageEstimate: 38,
    linkedinUrl: "https://linkedin.com/in/davidmin-patagonia",
    socialPresence: "high",
    vipScore: 57,
    tags: ["new", "young-professional", "outdoor-enthusiast", "sustainability"],
  },
  {
    name: "Feeney, Lorraine",
    phone: "518.884.3367",
    totalStays: 1,
    totalRevenue: 398,
    lastStay: "2025-04-12",
    nextArrival: "2026-07-25",
    nightlyRate: 199,
    nights: 2,
    roomType: "REGAL",
    bookingLeadDays: 112,
    guestSegment: "planner",
    enrichmentScore: 16,
    occupation: null,
    company: null,
    ageEstimate: 73,
    linkedinUrl: null,
    socialPresence: "none",
    vipScore: 17,
    tags: ["new", "retiree"],
  },
  {
    name: "Brooks, Tyrell",
    phone: "347.229.6615",
    totalStays: 1,
    totalRevenue: 538,
    lastStay: "2025-11-22",
    nextArrival: "2026-04-19",
    nightlyRate: 269,
    nights: 2,
    roomType: "JRSTE",
    bookingLeadDays: 9,
    guestSegment: "impulse",
    enrichmentScore: 84,
    occupation: "Personal Chef",
    company: "Independent",
    ageEstimate: 35,
    linkedinUrl: "https://linkedin.com/in/tyrellbrooks-chef",
    socialPresence: "moderate",
    vipScore: 43,
    tags: ["new", "young-professional", "f-and-b-industry"],
  },
  {
    name: "Sweeney, Kathleen",
    phone: "845.662.4423",
    totalStays: 5,
    totalRevenue: 6850,
    lastStay: "2025-12-07",
    nextArrival: "2026-04-08",
    nightlyRate: 269,
    nights: 2,
    roomType: "DEL2Q",
    bookingLeadDays: 55,
    guestSegment: "loyalist",
    enrichmentScore: 50,
    occupation: "Innkeeper",
    company: "The Phoenicia Inn",
    ageEstimate: 58,
    linkedinUrl: null,
    socialPresence: "moderate",
    vipScore: 83,
    tags: ["repeat", "high-value", "hospitality-insider", "local-business"],
  },
  {
    name: "Green, Marcus",
    phone: "929.447.1107",
    totalStays: 1,
    totalRevenue: 1047,
    lastStay: "2025-07-26",
    nextArrival: "2026-04-12",
    nightlyRate: 349,
    nights: 3,
    roomType: "IMPST",
    bookingLeadDays: 5,
    guestSegment: "impulse",
    enrichmentScore: 86,
    occupation: "Mountain Bike Coach",
    company: "Catskill Mountain Biking",
    ageEstimate: 34,
    linkedinUrl: "https://linkedin.com/in/marcusgreen-mtb",
    socialPresence: "high",
    vipScore: 50,
    tags: ["new", "young-professional", "outdoor-enthusiast", "local"],
  },
  {
    name: "Oberman, Claire",
    phone: "212.662.5538",
    totalStays: 1,
    totalRevenue: 598,
    lastStay: "2025-10-11",
    nextArrival: "2026-04-25",
    nightlyRate: 299,
    nights: 2,
    roomType: "ROYAL",
    bookingLeadDays: 28,
    guestSegment: "planner",
    enrichmentScore: 79,
    occupation: "Copywriter",
    company: "Wieden+Kennedy",
    ageEstimate: 31,
    linkedinUrl: "https://linkedin.com/in/claireoberman-copy",
    socialPresence: "moderate",
    vipScore: 44,
    tags: ["new", "young-professional", "creative"],
  },
];
