import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create test organization
  const org = await prisma.organization.upsert({
    where: { id: 'org_34cUVXYdLPmUUb6ijvXohVYEi1V' },
    update: {},
    create: {
      id: 'org_34cUVXYdLPmUUb6ijvXohVYEi1V',
      name: '23123123',
      slug: 'test-org',
    },
  });
  console.log('✅ Organization created:', org.name);

  // Create/update your user
  const user = await prisma.user.upsert({
    where: { id: 'user_2zssasQgWPFWcwIWnJbnVSputvM' },
    update: {
      organizationId: org.id,
      email: 'isaac@dealwire.ai',
      firstName: 'Test',
      lastName: 'Tester',
    },
    create: {
      id: 'user_2zssasQgWPFWcwIWnJbnVSputvM',
      email: 'isaac@dealwire.ai',
      firstName: 'Test',
      lastName: 'Tester',
      organizationId: org.id,
    },
  });
  console.log('✅ User created:', user.email);

  // Create test assets
  const assetData = [
    { address: '123 Main St', city: 'New York', state: 'NY', country: 'USA' },
    { address: '456 Broadway', city: 'New York', state: 'NY', country: 'USA' },
    { address: '789 Park Ave', city: 'New York', state: 'NY', country: 'USA' },
    { address: '100 Wall St', city: 'New York', state: 'NY', country: 'USA' },
    { address: '55 Water St', city: 'New York', state: 'NY', country: 'USA' },
    {
      address: '200 Lexington Ave',
      city: 'New York',
      state: 'NY',
      country: 'USA',
    },
    { address: '350 5th Ave', city: 'New York', state: 'NY', country: 'USA' },
    { address: '1 Penn Plaza', city: 'New York', state: 'NY', country: 'USA' },
    {
      address: '30 Hudson Yards',
      city: 'New York',
      state: 'NY',
      country: 'USA',
    },
    { address: '425 Park Ave', city: 'New York', state: 'NY', country: 'USA' },
    { address: '1745 Broadway', city: 'New York', state: 'NY', country: 'USA' },
    { address: '601 W 26th St', city: 'New York', state: 'NY', country: 'USA' },
    { address: '85 Broad St', city: 'New York', state: 'NY', country: 'USA' },
    { address: '250 Vesey St', city: 'New York', state: 'NY', country: 'USA' },
    { address: '11 Times Sq', city: 'New York', state: 'NY', country: 'USA' },
    { address: '101 Collins Ave', city: 'Miami', state: 'FL', country: 'USA' },
    { address: '500 Brickell Ave', city: 'Miami', state: 'FL', country: 'USA' },
    {
      address: '900 Biscayne Blvd',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
    },
    {
      address: '333 Las Olas Way',
      city: 'Fort Lauderdale',
      state: 'FL',
      country: 'USA',
    },
    {
      address: '8701 Collins Ave',
      city: 'Miami Beach',
      state: 'FL',
      country: 'USA',
    },
  ];

  const assets: { id: string }[] = [];
  for (const a of assetData) {
    const normalized = `${a.address.toUpperCase()}, ${a.city.toUpperCase()}, ${a.state}, ${a.country}`;
    const asset = await prisma.asset.upsert({
      where: { normalizedAddress: normalized },
      update: {},
      create: { ...a, normalizedAddress: normalized },
    });
    assets.push(asset);
  }
  console.log(`✅ ${assets.length} assets created`);

  // Create test contacts
  const contactData = [
    { email: 'broker1@example.com', firstName: 'John', lastName: 'Smith' },
    { email: 'broker2@example.com', firstName: 'Jane', lastName: 'Doe' },
    { email: 'deals@cbre.com', firstName: 'Michael', lastName: 'Chen' },
    { email: 'acquisitions@jll.com', firstName: 'Sarah', lastName: 'Johnson' },
    {
      email: 'listings@cushwake.com',
      firstName: 'David',
      lastName: 'Williams',
    },
    {
      email: 'broker@marcusmillichap.com',
      firstName: 'Robert',
      lastName: 'Garcia',
    },
    { email: 'deals@eastdil.com', firstName: 'Emily', lastName: 'Martinez' },
    { email: 'offers@hff.com', firstName: 'Daniel', lastName: 'Brown' },
    { email: 'sales@colliers.com', firstName: 'Amanda', lastName: 'Wilson' },
    { email: 'teaser@newmark.com', firstName: 'Chris', lastName: 'Taylor' },
  ];

  const contacts: { id: string }[] = [];
  for (const c of contactData) {
    const contact = await prisma.contact.upsert({
      where: { email: c.email },
      update: {},
      create: c,
    });
    contacts.push(contact);
  }
  console.log(`✅ ${contacts.length} contacts created`);

  // Create 35 test deals to exercise pagination (default page size = 20)
  const dealTemplates = [
    {
      subject: 'Off-Market Opportunity - 123 Main St Multifamily',
      decision: 'YES' as const,
      summary:
        'Strong cash-flowing multifamily in prime location. 6.5% cap rate, stable tenancy.',
    },
    {
      subject: 'Exclusive - 456 Broadway Office Building',
      decision: 'NO' as const,
      summary:
        'Office building with high vacancy. Below market cap rate but requires significant capex.',
      folder: 'Passed Deals',
    },
    {
      subject: 'New Listing - 789 Park Ave Luxury Condo',
      decision: 'YES' as const,
      summary:
        'Premium residential with strong demographics. 5.8% cap rate, trophy asset.',
    },
    {
      subject: 'Distressed Sale - 100 Wall St Mixed-Use',
      decision: 'YES' as const,
      summary:
        'Below replacement cost. Needs renovation but strong fundamentals. 7.2% cap rate.',
    },
    {
      subject: 'Portfolio Sale - 55 Water St Office Complex',
      decision: 'NO' as const,
      summary:
        'Large office complex with declining occupancy. Not aligned with current strategy.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Investment Opportunity - 200 Lexington Ave Retail',
      decision: 'YES' as const,
      summary:
        'Prime retail with long-term NNN leases. 5.5% cap rate, minimal management required.',
    },
    {
      subject: 'Offering Memorandum - 350 5th Ave Office Tower',
      decision: 'NO' as const,
      summary:
        'Iconic location but cap rate too low at 3.8%. Does not meet minimum yield requirements.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Teaser - 1 Penn Plaza Redevelopment',
      decision: 'YES' as const,
      summary:
        'Significant value-add potential. Current 4.5% cap rate with path to 7%+ after repositioning.',
    },
    {
      subject: 'Confidential - 30 Hudson Yards Class A Office',
      decision: 'YES' as const,
      summary:
        'Trophy asset in Hudson Yards. Strong tenant roster, 95% occupied. 5.2% cap rate.',
    },
    {
      subject: 'Price Reduction - 425 Park Ave Boutique Office',
      decision: 'NO' as const,
      summary:
        'Price reduced 15% but still above market. Tenant rollover risk in 2027.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Just Listed - 1745 Broadway Mixed-Use',
      decision: 'YES' as const,
      summary:
        'Retail and office combo with below-market rents. 6.0% cap rate, mark-to-market upside.',
    },
    {
      subject: 'Pocket Listing - 601 W 26th St Creative Office',
      decision: 'YES' as const,
      summary:
        'Chelsea creative office with tech tenants. 5.9% cap rate, strong rent growth trajectory.',
    },
    {
      subject: 'Offering - 85 Broad St FiDi Office',
      decision: 'NO' as const,
      summary:
        'FiDi office with dated finishes. Would require $50M+ in capex to reposition.',
      folder: 'Passed Deals',
    },
    {
      subject: 'For Sale - 250 Vesey St Waterfront Office',
      decision: 'YES' as const,
      summary:
        'Class A waterfront with views. 5.4% cap rate, long-term government tenant.',
    },
    {
      subject: 'Exclusive Listing - 11 Times Sq Flagship Retail',
      decision: 'NO' as const,
      summary:
        'Retail in Times Sq faces headwinds. Tourism recovery uncertain, high ask price.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Miami Opportunity - 101 Collins Ave Beachfront',
      decision: 'NO' as const,
      summary:
        'Outside target market (New York only). Pass per investment criteria.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Brickell Tower - 500 Brickell Ave Luxury Resi',
      decision: 'NO' as const,
      summary: 'Miami market - does not meet geographic criteria.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Waterfront Development - 900 Biscayne Blvd',
      decision: 'NO' as const,
      summary: 'Development deal in Miami. Outside geographic focus area.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Fort Lauderdale Mixed-Use - 333 Las Olas Way',
      decision: 'NO' as const,
      summary: 'South Florida mixed-use. Not in target geography.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Beachfront Condo - 8701 Collins Ave Miami Beach',
      decision: 'NO' as const,
      summary:
        'Luxury condo in Miami Beach. Automatic no per NY-only criteria.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Follow-Up: 123 Main St Updated Financials',
      decision: 'YES' as const,
      summary:
        'Updated pro forma confirms 6.8% stabilized cap rate. Recommend proceeding.',
    },
    {
      subject: 'RE: 789 Park Ave - Revised Offer Terms',
      decision: 'YES' as const,
      summary:
        'Seller accepted revised terms. Price now at $45M, 6.0% cap rate.',
    },
    {
      subject: 'New OM - 200 Lexington Ave Full Package',
      decision: 'YES' as const,
      summary:
        'Full OM received. Financials confirm 5.5% in-place, 6.2% pro forma cap rate.',
    },
    {
      subject: 'Price Update - 350 5th Ave Repriced',
      decision: 'NO' as const,
      summary:
        'Repriced at $120M but still 4.0% cap rate. Below our 5% minimum.',
      folder: 'Passed Deals',
    },
    {
      subject: 'BOV Request - 30 Hudson Yards Competitive Process',
      decision: 'YES' as const,
      summary:
        'Best and final round. Our analysis supports $95M valuation at 5.3% cap rate.',
    },
    {
      subject: 'RE: 1745 Broadway - Environmental Report',
      decision: 'YES' as const,
      summary:
        'Phase I environmental came back clean. No issues identified. Proceed with due diligence.',
    },
    {
      subject: 'Urgent: 601 W 26th St Multiple Offers',
      decision: 'YES' as const,
      summary:
        'Competitive situation developing. Broker confirms 3 offers in. Recommend aggressive bid.',
    },
    {
      subject: 'Update: 250 Vesey St Tenant Renewal Confirmed',
      decision: 'YES' as const,
      summary:
        'Government tenant renewed for 10 years. Cap rate now effectively 5.6% with certainty.',
    },
    {
      subject: 'Withdrawn - 425 Park Ave Off Market',
      decision: 'NO' as const,
      summary: 'Seller has withdrawn the listing. No longer available.',
      folder: 'Passed Deals',
    },
    {
      subject: 'RE: 85 Broad St - Counter Proposal',
      decision: 'NO' as const,
      summary:
        'Seller countered at $80M. Still too high given required capex. Passing.',
      folder: 'Passed Deals',
    },
    {
      subject: 'New Deal - 15 Central Park West Ultra-Luxury',
      decision: 'YES' as const,
      summary:
        'Rare opportunity at 15 CPW. Trophy residential, 4.8% cap rate but irreplaceable location.',
    },
    {
      subject: 'Teaser - 60 Wall St Conversion Opportunity',
      decision: 'YES' as const,
      summary:
        'Office-to-resi conversion play. Attractive basis at $200/SF. Strong residential demand.',
    },
    {
      subject: 'Off-Market - 220 Central Park South Penthouse',
      decision: 'YES' as const,
      summary:
        'Ultra-luxury penthouse unit. Comparable sales support 5.2% yield. Trophy asset.',
    },
    {
      subject: 'Portfolio - Midtown 5-Building Office Package',
      decision: 'NO' as const,
      summary:
        'Portfolio too large at $500M. Would exceed single-asset concentration limits.',
      folder: 'Passed Deals',
    },
    {
      subject: 'Teaser - SoHo Retail Portfolio (3 Properties)',
      decision: 'YES' as const,
      summary:
        'SoHo retail with below-market rents. Avg 5.7% cap rate with significant mark-to-market upside.',
    },
  ];

  for (let i = 0; i < dealTemplates.length; i++) {
    const t = dealTemplates[i];
    const assetIdx = i % assets.length;
    const contactIdx = i % contacts.length;
    // Spread deals across Jan-Feb 2026
    const dayOffset = i;
    const receivedAt = new Date(
      2026,
      0,
      5 + dayOffset,
      8 + (i % 12),
      (i * 17) % 60,
    );

    const dealId = `deal_seed_${i + 1}`;
    await prisma.deal.upsert({
      where: { id: dealId },
      update: {
        sourceSubject: t.subject,
        folderMovedTo: t.folder || null,
        assetId: assets[assetIdx].id,
        contactId: contacts[contactIdx].id,
        sourceReceivedAt: receivedAt,
      },
      create: {
        id: dealId,
        organizationId: org.id,
        receivedByUserId: user.id,
        sourceMessageId: `msg_seed_${i + 1}`,
        sourceFrom: contactData[contactIdx].email,
        sourceSubject: t.subject,
        sourceReceivedAt: receivedAt,
        detectionConfidence: 'high',
        detectionReason:
          'Email contains acquisition details and deal information',
        folderMovedTo: t.folder || null,
        assetId: assets[assetIdx].id,
        contactId: contacts[contactIdx].id,
      },
    });

    // Create InitialScreening record (the proper relation)
    await prisma.initialScreening.upsert({
      where: { dealId },
      update: {
        decision: t.decision,
        reason: t.summary,
      },
      create: {
        dealId,
        decision: t.decision,
        reason: t.summary,
      },
    });
  }

  // Clean up old seed deals with legacy IDs
  for (const legacyId of ['deal_1', 'deal_2', 'deal_3']) {
    await prisma.deal.deleteMany({ where: { id: legacyId } });
  }

  console.log(`✅ Created ${dealTemplates.length} test deals`);

  // Create screening preferences
  await prisma.screeningPreferences.upsert({
    where: { organizationId: org.id },
    update: {},
    create: {
      organizationId: org.id,
      companyName: 'Test Company',
      brandColor: '#3ECFA0',
      passedFolderName: 'Passed Deals',
      dealCriteria:
        'Must be in New York, cap rate > 5%, multifamily or office preferred',
      digestSchedule: '0 9 * * *',
      digestTimeZone: 'America/New_York',
    },
  });

  console.log('✅ Screening preferences created');

  // ── Clerk org (the one actually used via JWT) ──
  // The Clerk JWT sends org_2zstFyYG5TEEH3wroUvIak5oDyX — ensure it exists with parcels enabled
  const clerkOrg = await prisma.organization.upsert({
    where: { id: 'org_2zstFyYG5TEEH3wroUvIak5oDyX' },
    update: {
      featureFlags: { parcels: true, underwriting: true },
    },
    create: {
      id: 'org_2zstFyYG5TEEH3wroUvIak5oDyX',
      name: 'Dealwire Dev',
      slug: 'dealwire-dev',
      featureFlags: { parcels: true, underwriting: true },
    },
  });
  // Also enable parcels on the seed org
  await prisma.organization.update({
    where: { id: org.id },
    data: { featureFlags: { parcels: true, underwriting: true } },
  });
  console.log('✅ Feature flags enabled (parcels + underwriting)');

  // ── Parcels ──
  // Realistic NYC parcels across Brooklyn + Queens with varying distress levels,
  // skip trace states, lien data, and violations — mirrors what we see in prod.
  const parcelData = [
    // ── Brooklyn (borough=3), high distress, traced ──
    {
      bbl: '3012340001',
      borough: '3',
      block: '01234',
      lot: '0001',
      address: '145 ATLANTIC AVE',
      zipCode: '11201',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'C4',
      unitsTotal: 12,
      unitsRes: 12,
      buildingArea: 9600,
      lotArea: 2500,
      numFloors: 4,
      yearBuilt: 1925,
      ownerName: 'ATLANTIC REALTY LLC',
      zoneDist1: 'R6B',
      landUse: '02',
      assessTotal: 450000,
      taxClass: '2',
      estimatedMarketValue: 1000000,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: '90 Day Notice',
      waterDebtOnly: false,
      outstandingTaxBill: 18500,
      totalOutstandingBalance: 32000,
      violationsTotal: 42,
      violationsOpen: 15,
      violationsClassA: 8,
      violationsClassB: 22,
      violationsClassC: 12,
      violationsPerUnit: 1.25,
      distressScore: 82,
      lienSaleAmount: 45000,
      lienRedemptiveValue: 52000,
      lienServicer: 'MTAG',
      lienRedeemed: false,
      lienForeclosureStatus: 'Referred',
      lienSaleDate: '2024-05-15',
      lienTrustVintage: '2024-A',
      lienMatchConfidence: 'exact',
      lienMatchGroupSize: 1,
      ownerPhones: [{ number: '(718) 555-0101', type: 'mobile', rank: 1 }],
      ownerEmails: ['atlantic.realty@example.com'],
      skipTraceStatus: 'found',
      skipTracedAt: new Date('2026-03-01'),
    },
    {
      bbl: '3045670023',
      borough: '3',
      block: '04567',
      lot: '0023',
      address: '312 BEDFORD AVE',
      zipCode: '11211',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'C2',
      unitsTotal: 6,
      unitsRes: 6,
      buildingArea: 4800,
      lotArea: 2000,
      numFloors: 3,
      yearBuilt: 1930,
      ownerName: 'BEDFORD HOLDINGS INC',
      zoneDist1: 'R6',
      landUse: '02',
      assessTotal: 380000,
      taxClass: '2',
      estimatedMarketValue: 844000,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: 'Lien Sale',
      waterDebtOnly: false,
      outstandingTaxBill: 24000,
      totalOutstandingBalance: 41000,
      violationsTotal: 55,
      violationsOpen: 22,
      violationsClassA: 10,
      violationsClassB: 28,
      violationsClassC: 17,
      violationsPerUnit: 3.67,
      distressScore: 91,
      lienSaleAmount: 38000,
      lienRedemptiveValue: 44500,
      lienServicer: 'Tower',
      lienRedeemed: false,
      lienForeclosureStatus: 'Active',
      lienSaleDate: '2023-11-20',
      lienTrustVintage: '2023-B',
      lienMatchConfidence: 'exact',
      lienMatchGroupSize: 1,
      ownerPhones: [
        { number: '(718) 555-0202', type: 'landline', rank: 1 },
        { number: '(917) 555-0203', type: 'mobile', rank: 2 },
      ],
      ownerEmails: ['info@bedfordholdings.com'],
      skipTraceStatus: 'found',
      skipTracedAt: new Date('2026-02-15'),
    },
    // ── Brooklyn, medium distress, not traced ──
    {
      bbl: '3056780045',
      borough: '3',
      block: '05678',
      lot: '0045',
      address: '890 FLATBUSH AVE',
      zipCode: '11226',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'A5',
      unitsTotal: 2,
      unitsRes: 2,
      buildingArea: 2400,
      lotArea: 3000,
      numFloors: 2,
      yearBuilt: 1940,
      ownerName: 'JAMES THOMPSON',
      zoneDist1: 'R5',
      landUse: '01',
      assessTotal: 280000,
      taxClass: '1',
      estimatedMarketValue: 4666667,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: '90 Day Notice',
      waterDebtOnly: true,
      outstandingTaxBill: 5200,
      totalOutstandingBalance: 8900,
      violationsTotal: 8,
      violationsOpen: 3,
      violationsClassA: 2,
      violationsClassB: 4,
      violationsClassC: 2,
      violationsPerUnit: 1.5,
      distressScore: 48,
      lienSaleAmount: null,
      lienRedemptiveValue: null,
      lienServicer: null,
      lienRedeemed: null,
      lienForeclosureStatus: null,
      lienSaleDate: null,
      lienTrustVintage: null,
      lienMatchConfidence: null,
      lienMatchGroupSize: null,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: null,
      skipTracedAt: null,
    },
    {
      bbl: '3067890012',
      borough: '3',
      block: '06789',
      lot: '0012',
      address: '1455 FULTON ST',
      zipCode: '11216',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'C1',
      unitsTotal: 8,
      unitsRes: 8,
      buildingArea: 6400,
      lotArea: 2200,
      numFloors: 4,
      yearBuilt: 1920,
      ownerName: 'FULTON STREET MGMT CORP',
      zoneDist1: 'R7A',
      landUse: '02',
      assessTotal: 420000,
      taxClass: '2',
      estimatedMarketValue: 933333,
      isCoopExcluded: false,
      hasActiveLien: false,
      lienCycle: null,
      waterDebtOnly: false,
      outstandingTaxBill: 12000,
      totalOutstandingBalance: 12000,
      violationsTotal: 18,
      violationsOpen: 7,
      violationsClassA: 5,
      violationsClassB: 9,
      violationsClassC: 4,
      violationsPerUnit: 0.88,
      distressScore: 55,
      lienSaleAmount: 22000,
      lienRedemptiveValue: 25000,
      lienServicer: 'MTAG',
      lienRedeemed: true,
      lienForeclosureStatus: null,
      lienSaleDate: '2022-05-10',
      lienTrustVintage: '2022-A',
      lienMatchConfidence: 'group_small',
      lienMatchGroupSize: 3,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: null,
      skipTracedAt: null,
    },
    // ── Brooklyn, low distress, traced with no phone found ──
    {
      bbl: '3078900034',
      borough: '3',
      block: '07890',
      lot: '0034',
      address: '225 PARK PL',
      zipCode: '11238',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'B1',
      unitsTotal: 2,
      unitsRes: 2,
      buildingArea: 2800,
      lotArea: 2000,
      numFloors: 2,
      yearBuilt: 1910,
      ownerName: 'MARIA GONZALEZ',
      zoneDist1: 'R6B',
      landUse: '01',
      assessTotal: 320000,
      taxClass: '1',
      estimatedMarketValue: 5333333,
      isCoopExcluded: false,
      hasActiveLien: false,
      lienCycle: null,
      waterDebtOnly: false,
      outstandingTaxBill: 0,
      totalOutstandingBalance: 0,
      violationsTotal: 3,
      violationsOpen: 1,
      violationsClassA: 1,
      violationsClassB: 2,
      violationsClassC: 0,
      violationsPerUnit: 0.5,
      distressScore: 18,
      lienSaleAmount: null,
      lienRedemptiveValue: null,
      lienServicer: null,
      lienRedeemed: null,
      lienForeclosureStatus: null,
      lienSaleDate: null,
      lienTrustVintage: null,
      lienMatchConfidence: null,
      lienMatchGroupSize: null,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: 'not_found',
      skipTracedAt: new Date('2026-03-10'),
    },
    // ── Brooklyn, pending skip trace ──
    {
      bbl: '3089010056',
      borough: '3',
      block: '08901',
      lot: '0056',
      address: '567 NOSTRAND AVE',
      zipCode: '11216',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'C6',
      unitsTotal: 16,
      unitsRes: 16,
      buildingArea: 12800,
      lotArea: 3200,
      numFloors: 4,
      yearBuilt: 1935,
      ownerName: 'NOSTRAND PROPERTIES LLC',
      zoneDist1: 'R7A',
      landUse: '02',
      assessTotal: 650000,
      taxClass: '2',
      estimatedMarketValue: 1444444,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: 'Lien Sale',
      waterDebtOnly: false,
      outstandingTaxBill: 35000,
      totalOutstandingBalance: 58000,
      violationsTotal: 67,
      violationsOpen: 28,
      violationsClassA: 12,
      violationsClassB: 30,
      violationsClassC: 25,
      violationsPerUnit: 1.75,
      distressScore: 88,
      lienSaleAmount: 62000,
      lienRedemptiveValue: 71000,
      lienServicer: 'Tower',
      lienRedeemed: false,
      lienForeclosureStatus: 'Active',
      lienSaleDate: '2024-05-15',
      lienTrustVintage: '2024-A',
      lienMatchConfidence: 'exact',
      lienMatchGroupSize: 1,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: 'pending',
      skipTracedAt: null,
    },
    // ── Queens (borough=4), high distress, traced ──
    {
      bbl: '4012340078',
      borough: '4',
      block: '01234',
      lot: '0078',
      address: '94-20 QUEENS BLVD',
      zipCode: '11373',
      city: 'Queens',
      state: 'NY',
      buildingClass: 'C4',
      unitsTotal: 20,
      unitsRes: 20,
      buildingArea: 16000,
      lotArea: 4000,
      numFloors: 5,
      yearBuilt: 1928,
      ownerName: 'QUEENS BLVD ASSOCIATES',
      zoneDist1: 'R7A',
      landUse: '02',
      assessTotal: 850000,
      taxClass: '2',
      estimatedMarketValue: 1888889,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: 'Lien Sale',
      waterDebtOnly: false,
      outstandingTaxBill: 42000,
      totalOutstandingBalance: 67000,
      violationsTotal: 78,
      violationsOpen: 35,
      violationsClassA: 15,
      violationsClassB: 38,
      violationsClassC: 25,
      violationsPerUnit: 1.75,
      distressScore: 95,
      lienSaleAmount: 85000,
      lienRedemptiveValue: 98000,
      lienServicer: 'MTAG',
      lienRedeemed: false,
      lienForeclosureStatus: 'Referred',
      lienSaleDate: '2023-11-20',
      lienTrustVintage: '2023-B',
      lienMatchConfidence: 'exact',
      lienMatchGroupSize: 1,
      ownerPhones: [
        { number: '(718) 555-0401', type: 'mobile', rank: 1 },
        { number: '(347) 555-0402', type: 'landline', rank: 2 },
      ],
      ownerEmails: ['queensblvd@example.com'],
      skipTraceStatus: 'found',
      skipTracedAt: new Date('2026-02-20'),
    },
    {
      bbl: '4023450089',
      borough: '4',
      block: '02345',
      lot: '0089',
      address: '37-15 BROADWAY',
      zipCode: '11103',
      city: 'Queens',
      state: 'NY',
      buildingClass: 'C2',
      unitsTotal: 6,
      unitsRes: 6,
      buildingArea: 4800,
      lotArea: 2500,
      numFloors: 3,
      yearBuilt: 1932,
      ownerName: 'BROADWAY ASTORIA LLC',
      zoneDist1: 'R6',
      landUse: '02',
      assessTotal: 360000,
      taxClass: '2',
      estimatedMarketValue: 800000,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: '90 Day Notice',
      waterDebtOnly: false,
      outstandingTaxBill: 15000,
      totalOutstandingBalance: 28000,
      violationsTotal: 34,
      violationsOpen: 14,
      violationsClassA: 6,
      violationsClassB: 18,
      violationsClassC: 10,
      violationsPerUnit: 2.33,
      distressScore: 76,
      lienSaleAmount: 30000,
      lienRedemptiveValue: 35000,
      lienServicer: 'Tower',
      lienRedeemed: false,
      lienForeclosureStatus: null,
      lienSaleDate: '2024-05-15',
      lienTrustVintage: '2024-A',
      lienMatchConfidence: 'group_small',
      lienMatchGroupSize: 2,
      ownerPhones: [{ number: '(718) 555-0501', type: 'mobile', rank: 1 }],
      ownerEmails: [],
      skipTraceStatus: 'found',
      skipTracedAt: new Date('2026-03-05'),
    },
    // ── Queens, medium distress, not traced ──
    {
      bbl: '4034560001',
      borough: '4',
      block: '03456',
      lot: '0001',
      address: '108-22 JAMAICA AVE',
      zipCode: '11418',
      city: 'Queens',
      state: 'NY',
      buildingClass: 'K4',
      unitsTotal: 0,
      unitsRes: 0,
      buildingArea: 8500,
      lotArea: 5000,
      numFloors: 2,
      yearBuilt: 1955,
      ownerName: 'JAMAICA COMMERCIAL CORP',
      zoneDist1: 'C4-3A',
      landUse: '05',
      assessTotal: 520000,
      taxClass: '4',
      estimatedMarketValue: 1155556,
      isCoopExcluded: false,
      hasActiveLien: false,
      lienCycle: null,
      waterDebtOnly: false,
      outstandingTaxBill: 8500,
      totalOutstandingBalance: 8500,
      violationsTotal: 0,
      violationsOpen: 0,
      violationsClassA: 0,
      violationsClassB: 0,
      violationsClassC: 0,
      violationsPerUnit: null,
      distressScore: 35,
      lienSaleAmount: null,
      lienRedemptiveValue: null,
      lienServicer: null,
      lienRedeemed: null,
      lienForeclosureStatus: null,
      lienSaleDate: null,
      lienTrustVintage: null,
      lienMatchConfidence: null,
      lienMatchGroupSize: null,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: null,
      skipTracedAt: null,
    },
    {
      bbl: '4045670023',
      borough: '4',
      block: '04567',
      lot: '0023',
      address: '65-10 MYRTLE AVE',
      zipCode: '11385',
      city: 'Queens',
      state: 'NY',
      buildingClass: 'A5',
      unitsTotal: 2,
      unitsRes: 2,
      buildingArea: 2200,
      lotArea: 2000,
      numFloors: 2,
      yearBuilt: 1945,
      ownerName: 'CHEN FAMILY TRUST',
      zoneDist1: 'R5',
      landUse: '01',
      assessTotal: 240000,
      taxClass: '1',
      estimatedMarketValue: 4000000,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: '90 Day Notice',
      waterDebtOnly: true,
      outstandingTaxBill: 3200,
      totalOutstandingBalance: 6800,
      violationsTotal: 5,
      violationsOpen: 2,
      violationsClassA: 2,
      violationsClassB: 2,
      violationsClassC: 1,
      violationsPerUnit: 1.0,
      distressScore: 42,
      lienSaleAmount: null,
      lienRedemptiveValue: null,
      lienServicer: null,
      lienRedeemed: null,
      lienForeclosureStatus: null,
      lienSaleDate: null,
      lienTrustVintage: null,
      lienMatchConfidence: null,
      lienMatchGroupSize: null,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: null,
      skipTracedAt: null,
    },
    // ── Queens, skip trace error ──
    {
      bbl: '4056780045',
      borough: '4',
      block: '05678',
      lot: '0045',
      address: '41-25 KISSENA BLVD',
      zipCode: '11355',
      city: 'Queens',
      state: 'NY',
      buildingClass: 'C1',
      unitsTotal: 10,
      unitsRes: 10,
      buildingArea: 8000,
      lotArea: 2800,
      numFloors: 4,
      yearBuilt: 1938,
      ownerName: 'KISSENA MGMT INC',
      zoneDist1: 'R6',
      landUse: '02',
      assessTotal: 480000,
      taxClass: '2',
      estimatedMarketValue: 1066667,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: 'Lien Sale',
      waterDebtOnly: false,
      outstandingTaxBill: 22000,
      totalOutstandingBalance: 38000,
      violationsTotal: 45,
      violationsOpen: 19,
      violationsClassA: 8,
      violationsClassB: 22,
      violationsClassC: 15,
      violationsPerUnit: 1.9,
      distressScore: 79,
      lienSaleAmount: 55000,
      lienRedemptiveValue: 63000,
      lienServicer: 'MTAG',
      lienRedeemed: false,
      lienForeclosureStatus: 'Active',
      lienSaleDate: '2023-11-20',
      lienTrustVintage: '2023-B',
      lienMatchConfidence: 'exact',
      lienMatchGroupSize: 1,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: 'error',
      skipTracedAt: new Date('2026-03-12'),
    },
    // ── Manhattan (borough=1), low distress, clean ──
    {
      bbl: '1012340056',
      borough: '1',
      block: '01234',
      lot: '0056',
      address: '145 E 15TH ST',
      zipCode: '10003',
      city: 'New York',
      state: 'NY',
      buildingClass: 'C7',
      unitsTotal: 24,
      unitsRes: 24,
      buildingArea: 19200,
      lotArea: 5000,
      numFloors: 6,
      yearBuilt: 1915,
      ownerName: 'GRAMERCY PARK OWNERS LLC',
      zoneDist1: 'R8B',
      landUse: '02',
      assessTotal: 1200000,
      taxClass: '2',
      estimatedMarketValue: 2666667,
      isCoopExcluded: false,
      hasActiveLien: false,
      lienCycle: null,
      waterDebtOnly: false,
      outstandingTaxBill: 0,
      totalOutstandingBalance: 0,
      violationsTotal: 6,
      violationsOpen: 2,
      violationsClassA: 2,
      violationsClassB: 3,
      violationsClassC: 1,
      violationsPerUnit: 0.08,
      distressScore: 12,
      lienSaleAmount: null,
      lienRedemptiveValue: null,
      lienServicer: null,
      lienRedeemed: null,
      lienForeclosureStatus: null,
      lienSaleDate: null,
      lienTrustVintage: null,
      lienMatchConfidence: null,
      lienMatchGroupSize: null,
      ownerPhones: [{ number: '(212) 555-0101', type: 'landline', rank: 1 }],
      ownerEmails: ['gramercy@example.com'],
      skipTraceStatus: 'found',
      skipTracedAt: new Date('2026-03-15'),
    },
    // ── Brooklyn, large group estimate lien ──
    {
      bbl: '3091230067',
      borough: '3',
      block: '09123',
      lot: '0067',
      address: '1820 PITKIN AVE',
      zipCode: '11212',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'C4',
      unitsTotal: 14,
      unitsRes: 14,
      buildingArea: 11200,
      lotArea: 2800,
      numFloors: 4,
      yearBuilt: 1922,
      ownerName: 'PITKIN AVENUE ASSOC',
      zoneDist1: 'R6',
      landUse: '02',
      assessTotal: 550000,
      taxClass: '2',
      estimatedMarketValue: 1222222,
      isCoopExcluded: false,
      hasActiveLien: true,
      lienCycle: 'Lien Sale',
      waterDebtOnly: false,
      outstandingTaxBill: 28000,
      totalOutstandingBalance: 45000,
      violationsTotal: 52,
      violationsOpen: 20,
      violationsClassA: 10,
      violationsClassB: 25,
      violationsClassC: 17,
      violationsPerUnit: 1.43,
      distressScore: 85,
      lienSaleAmount: 120000,
      lienRedemptiveValue: 140000,
      lienServicer: 'Tower',
      lienRedeemed: false,
      lienForeclosureStatus: 'Referred',
      lienSaleDate: '2024-05-15',
      lienTrustVintage: '2024-A',
      lienMatchConfidence: 'group_large',
      lienMatchGroupSize: 8,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: null,
      skipTracedAt: null,
    },
    // ── Brooklyn, no violations, no lien — minimal data ──
    {
      bbl: '3102340078',
      borough: '3',
      block: '10234',
      lot: '0078',
      address: '402 HENRY ST',
      zipCode: '11201',
      city: 'Brooklyn',
      state: 'NY',
      buildingClass: 'B2',
      unitsTotal: 2,
      unitsRes: 2,
      buildingArea: 3000,
      lotArea: 1800,
      numFloors: 3,
      yearBuilt: 1890,
      ownerName: 'HENRY ST PARTNERS',
      zoneDist1: 'R6',
      landUse: '01',
      assessTotal: 350000,
      taxClass: '1',
      estimatedMarketValue: 5833333,
      isCoopExcluded: false,
      hasActiveLien: false,
      lienCycle: null,
      waterDebtOnly: false,
      outstandingTaxBill: 0,
      totalOutstandingBalance: 0,
      violationsTotal: 0,
      violationsOpen: 0,
      violationsClassA: 0,
      violationsClassB: 0,
      violationsClassC: 0,
      violationsPerUnit: 0,
      distressScore: 5,
      lienSaleAmount: null,
      lienRedemptiveValue: null,
      lienServicer: null,
      lienRedeemed: null,
      lienForeclosureStatus: null,
      lienSaleDate: null,
      lienTrustVintage: null,
      lienMatchConfidence: null,
      lienMatchGroupSize: null,
      ownerPhones: null,
      ownerEmails: null,
      skipTraceStatus: null,
      skipTracedAt: null,
    },
    // ── Queens, redeemed lien ──
    {
      bbl: '4067890034',
      borough: '4',
      block: '06789',
      lot: '0034',
      address: '88-12 SUTPHIN BLVD',
      zipCode: '11435',
      city: 'Queens',
      state: 'NY',
      buildingClass: 'C2',
      unitsTotal: 8,
      unitsRes: 8,
      buildingArea: 6400,
      lotArea: 2400,
      numFloors: 3,
      yearBuilt: 1942,
      ownerName: 'SUTPHIN REALTY GROUP',
      zoneDist1: 'R6',
      landUse: '02',
      assessTotal: 400000,
      taxClass: '2',
      estimatedMarketValue: 888889,
      isCoopExcluded: false,
      hasActiveLien: false,
      lienCycle: null,
      waterDebtOnly: false,
      outstandingTaxBill: 2000,
      totalOutstandingBalance: 2000,
      violationsTotal: 22,
      violationsOpen: 5,
      violationsClassA: 4,
      violationsClassB: 12,
      violationsClassC: 6,
      violationsPerUnit: 0.63,
      distressScore: 30,
      lienSaleAmount: 18000,
      lienRedemptiveValue: 0,
      lienServicer: 'MTAG',
      lienRedeemed: true,
      lienForeclosureStatus: null,
      lienSaleDate: '2021-11-15',
      lienTrustVintage: '2021-B',
      lienMatchConfidence: 'exact',
      lienMatchGroupSize: 1,
      ownerPhones: [{ number: '(718) 555-0601', type: 'mobile', rank: 1 }],
      ownerEmails: ['sutphin@example.com'],
      skipTraceStatus: 'found',
      skipTracedAt: new Date('2026-03-08'),
    },
  ];

  const now = new Date();
  for (const p of parcelData) {
    const { ownerPhones, ownerEmails, skipTracedAt, ...rest } = p;
    await prisma.parcel.upsert({
      where: { bbl: p.bbl },
      update: {
        ...rest,
        ownerPhones: ownerPhones ?? undefined,
        ownerEmails: ownerEmails ?? undefined,
        skipTracedAt: skipTracedAt ?? undefined,
        violationsSyncedAt: p.violationsTotal > 0 ? now : null,
        plutoSyncedAt: now,
        liensSyncedAt: p.hasActiveLien ? now : null,
        nyctlSyncedAt: p.lienSaleAmount != null ? now : null,
      },
      create: {
        ...rest,
        ownerPhones: ownerPhones ?? undefined,
        ownerEmails: ownerEmails ?? undefined,
        skipTracedAt: skipTracedAt ?? undefined,
        violationsSyncedAt: p.violationsTotal > 0 ? now : null,
        plutoSyncedAt: now,
        liensSyncedAt: p.hasActiveLien ? now : null,
        nyctlSyncedAt: p.lienSaleAmount != null ? now : null,
      },
    });
  }
  console.log(`✅ ${parcelData.length} parcels created`);

  // Create OrgSkipTrace records for traced parcels (unlocks phone visibility for the org)
  const tracedBbls = parcelData
    .filter((p) => p.skipTraceStatus === 'found')
    .map((p) => p.bbl);
  for (const bbl of tracedBbls) {
    const parcel = await prisma.parcel.findUnique({
      where: { bbl },
      select: { id: true },
    });
    if (!parcel) continue;
    for (const orgId of [org.id, clerkOrg.id]) {
      await prisma.orgSkipTrace.upsert({
        where: {
          parcelId_organizationId: {
            parcelId: parcel.id,
            organizationId: orgId,
          },
        },
        update: {},
        create: { parcelId: parcel.id, organizationId: orgId },
      });
    }
  }
  console.log(
    `✅ OrgSkipTrace records created for ${tracedBbls.length} parcels`,
  );

  console.log('\n🎉 Seeding complete!');
  console.log('\nYou can now:');
  console.log('  - Sign in at http://localhost:3000/sign-in');
  console.log('  - View dashboard at http://localhost:3000/dashboard');
  console.log('  - View parcels at http://localhost:3000/public-data/parcels');
  console.log('  - View deals via API at http://localhost:3001/deals');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
