export type ProjectType =
  | "Multifamily"
  | "Mixed-Use"
  | "Condo"
  | "Hospitality"
  | "Office Conversion";

export type ApprovalStatus =
  | "Permits Approved"
  | "Site Plan Approved"
  | "Entitled"
  | "Under Review";

export type OutreachStatus = "Not Reached" | "Drafted" | "Sent";

export interface Project {
  project_name: string;
  developer: string;
  city: "Los Angeles" | "Miami" | "West Palm Beach" | "Seattle";
  submarket: string;
  address: string;
  project_type: ProjectType;
  units: number;
  gsf: number;
  est_project_cost_m: number;
  est_loan_need_m: number;
  approval_status: ApprovalStatus;
  announcement_date: string;
  source: string;
  source_headline: string;
  source_url: string;
  developer_track_record_score: number;
  developer_active_projects: number;
  prior_lender: string;
  contact_name: string;
  contact_title: string;
  contact_email: string;
  origination_score: number;
  outreach_status: OutreachStatus;
  draft_email: string;
}

const draft = (
  contactFirst: string,
  developer: string,
  projectName: string,
  loanM: number,
  units: number,
  city: string,
  hook: string,
): string =>
  `Subject: ${projectName} — construction financing\n\n${contactFirst},\n\nSaw the announcement on ${projectName} — congrats on getting through entitlement. ${hook}\n\nMadison Realty Capital has been one of the most active construction lenders in ${city} over the last few cycles, and a ~$${loanM}M senior construction facility for a ${units}-unit project is squarely in our sweet spot. We close balance-sheet, no syndication required, and have closed in 30 days when needed.\n\nWould a 15-minute call next week make sense to walk through what ${developer} is targeting on terms? Happy to send our recent ${city} comps in advance.\n\nBest,\nMarc Schwartz\nManaging Director, Originations & Acquisitions\nMadison Realty Capital`;

export const projects: Project[] = [
  // ── LOS ANGELES ────────────────────────────────────────────
  {
    project_name: "1500 Vermont",
    developer: "Onni Group",
    city: "Los Angeles",
    submarket: "Koreatown",
    address: "1500 S Vermont Ave, Los Angeles, CA",
    project_type: "Multifamily",
    units: 312,
    gsf: 358000,
    est_project_cost_m: 198,
    est_loan_need_m: 138,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-22",
    source: "Urbanize LA",
    source_headline: "Onni Group secures permits for 312-unit Koreatown tower",
    source_url: "https://urbanize.la/post/onni-1500-vermont",
    developer_track_record_score: 88,
    developer_active_projects: 11,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Beau Jarvis",
    contact_title: "President, Onni Group",
    contact_email: "bjarvis@onni.com",
    origination_score: 87,
    outreach_status: "Drafted",
    draft_email: draft(
      "Beau",
      "Onni",
      "1500 Vermont",
      138,
      312,
      "Los Angeles",
      "Koreatown is exactly where we'd want to be on a Class A multifamily right now — supply pipeline is finally tightening and the rent comps you're underwriting look defensible.",
    ),
  },
  {
    project_name: "The Cumberland",
    developer: "Lendlease",
    city: "Los Angeles",
    submarket: "Hollywood",
    address: "1601 N Vine St, Los Angeles, CA",
    project_type: "Mixed-Use",
    units: 280,
    gsf: 412000,
    est_project_cost_m: 245,
    est_loan_need_m: 172,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-18",
    source: "LA Business Journal",
    source_headline: "Lendlease moves forward on Hollywood mixed-use tower",
    source_url: "https://labusinessjournal.com/cumberland-hollywood",
    developer_track_record_score: 92,
    developer_active_projects: 7,
    prior_lender: "First-time relationship",
    contact_name: "Andrew Skinner",
    contact_title: "Head of Americas, Lendlease",
    contact_email: "askinner@lendlease.com",
    origination_score: 91,
    outreach_status: "Drafted",
    draft_email: draft(
      "Andrew",
      "Lendlease",
      "The Cumberland",
      172,
      280,
      "Los Angeles",
      "Mixed-use Class A in core Hollywood is a category we've been wanting more exposure to — the ground-floor retail along Vine should hold up well even in a softer leasing environment.",
    ),
  },
  {
    project_name: "Westlake Heights",
    developer: "Holland Partner Group",
    city: "Los Angeles",
    submarket: "Westlake",
    address: "650 S Westlake Ave, Los Angeles, CA",
    project_type: "Multifamily",
    units: 247,
    gsf: 281000,
    est_project_cost_m: 156,
    est_loan_need_m: 109,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-15",
    source: "The Real Deal LA",
    source_headline: "Holland Partner files for 247-unit Westlake project",
    source_url: "https://therealdeal.com/la/holland-westlake",
    developer_track_record_score: 85,
    developer_active_projects: 14,
    prior_lender: "Existing relationship: Wells Fargo",
    contact_name: "Tom Parsons",
    contact_title: "EVP Development, Holland Partner",
    contact_email: "tparsons@hollandpartnergroup.com",
    origination_score: 82,
    outreach_status: "Drafted",
    draft_email: draft(
      "Tom",
      "Holland Partner",
      "Westlake Heights",
      109,
      247,
      "Los Angeles",
      "Westlake basis is some of the most attractive in the LA core right now — the fact that you have permits in hand puts you ahead of nearly everyone else underwriting this submarket.",
    ),
  },
  {
    project_name: "DTLA Grand",
    developer: "Crescent Heights",
    city: "Los Angeles",
    submarket: "Downtown LA",
    address: "1100 S Grand Ave, Los Angeles, CA",
    project_type: "Condo",
    units: 410,
    gsf: 612000,
    est_project_cost_m: 388,
    est_loan_need_m: 272,
    approval_status: "Entitled",
    announcement_date: "2026-04-10",
    source: "Urbanize LA",
    source_headline: "Crescent Heights advances 410-unit DTLA condo tower",
    source_url: "https://urbanize.la/post/dtla-grand",
    developer_track_record_score: 95,
    developer_active_projects: 9,
    prior_lender: "Existing relationship: JPMorgan",
    contact_name: "Russell Galbut",
    contact_title: "Chairman, Crescent Heights",
    contact_email: "rgalbut@crescentheights.com",
    origination_score: 84,
    outreach_status: "Drafted",
    draft_email: draft(
      "Russell",
      "Crescent Heights",
      "DTLA Grand",
      272,
      410,
      "Los Angeles",
      "DTLA condo is a tough capital market right now, but a sponsor with your track record and a 410-unit Class A product is exactly the kind of profile we'd want to back through the construction phase.",
    ),
  },
  {
    project_name: "The Lina",
    developer: "Mill Creek Residential",
    city: "Los Angeles",
    submarket: "Mid-Wilshire",
    address: "5455 Wilshire Blvd, Los Angeles, CA",
    project_type: "Multifamily",
    units: 195,
    gsf: 218000,
    est_project_cost_m: 124,
    est_loan_need_m: 87,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-08",
    source: "Bisnow LA",
    source_headline: "Mill Creek lines up 195-unit Mid-Wilshire build",
    source_url: "https://bisnow.com/la/mill-creek-lina",
    developer_track_record_score: 80,
    developer_active_projects: 22,
    prior_lender: "Existing relationship: PNC",
    contact_name: "William MacDonald",
    contact_title: "Managing Director, Mill Creek",
    contact_email: "wmacdonald@millcreekplaces.com",
    origination_score: 78,
    outreach_status: "Not Reached",
    draft_email: draft(
      "William",
      "Mill Creek",
      "The Lina",
      87,
      195,
      "Los Angeles",
      "Mid-Wilshire 195-unit pencils well at today's costs and your basis here looks attractive — exactly the project profile we want exposure to right now.",
    ),
  },
  {
    project_name: "Culver Crossing",
    developer: "Carmel Partners",
    city: "Los Angeles",
    submarket: "Culver City",
    address: "9300 Venice Blvd, Culver City, CA",
    project_type: "Mixed-Use",
    units: 168,
    gsf: 245000,
    est_project_cost_m: 142,
    est_loan_need_m: 99,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-05",
    source: "LA Business Journal",
    source_headline: "Carmel Partners advances Culver mixed-use site",
    source_url: "https://labusinessjournal.com/carmel-culver",
    developer_track_record_score: 87,
    developer_active_projects: 8,
    prior_lender: "First-time relationship",
    contact_name: "Ron Zeff",
    contact_title: "CEO, Carmel Partners",
    contact_email: "rzeff@carmelpartners.com",
    origination_score: 81,
    outreach_status: "Drafted",
    draft_email: draft(
      "Ron",
      "Carmel Partners",
      "Culver Crossing",
      99,
      168,
      "Los Angeles",
      "Culver continues to be one of the most resilient submarkets in LA, and we'd love to put a first-time facility together for Carmel here.",
    ),
  },
  {
    project_name: "Pico Boulevard Lofts",
    developer: "Wood Partners",
    city: "Los Angeles",
    submarket: "Mid-City",
    address: "5100 W Pico Blvd, Los Angeles, CA",
    project_type: "Multifamily",
    units: 134,
    gsf: 158000,
    est_project_cost_m: 88,
    est_loan_need_m: 62,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-02",
    source: "The Real Deal LA",
    source_headline: "Wood Partners files for 134-unit Pico project",
    source_url: "https://therealdeal.com/la/wood-pico",
    developer_track_record_score: 78,
    developer_active_projects: 18,
    prior_lender: "Existing relationship: Truist",
    contact_name: "Joe Keough",
    contact_title: "Managing Director, Wood Partners",
    contact_email: "jkeough@woodpartners.com",
    origination_score: 72,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Joe",
      "Wood Partners",
      "Pico Boulevard Lofts",
      62,
      134,
      "Los Angeles",
      "Permits in hand on a 134-unit on Pico is a clean capital story — would love to get into the mix on construction financing.",
    ),
  },
  {
    project_name: "The Marina Tower",
    developer: "AECOM Capital",
    city: "Los Angeles",
    submarket: "Marina del Rey",
    address: "13700 Marina Pointe Dr, Marina del Rey, CA",
    project_type: "Multifamily",
    units: 326,
    gsf: 401000,
    est_project_cost_m: 268,
    est_loan_need_m: 188,
    approval_status: "Entitled",
    announcement_date: "2026-03-28",
    source: "Urbanize LA",
    source_headline: "AECOM Capital entitles 326-unit Marina del Rey tower",
    source_url: "https://urbanize.la/post/aecom-marina",
    developer_track_record_score: 82,
    developer_active_projects: 6,
    prior_lender: "First-time relationship",
    contact_name: "Warren Wachsberger",
    contact_title: "CEO, AECOM Capital",
    contact_email: "wwachsberger@aecom.com",
    origination_score: 79,
    outreach_status: "Drafted",
    draft_email: draft(
      "Warren",
      "AECOM Capital",
      "The Marina Tower",
      188,
      326,
      "Los Angeles",
      "Marina del Rey waterfront product at 326 units is an enviable site — we'd be very interested in being your construction lender on this one.",
    ),
  },
  {
    project_name: "Hollywood & Highland Phase II",
    developer: "DJM Capital Partners",
    city: "Los Angeles",
    submarket: "Hollywood",
    address: "6801 Hollywood Blvd, Los Angeles, CA",
    project_type: "Mixed-Use",
    units: 220,
    gsf: 380000,
    est_project_cost_m: 215,
    est_loan_need_m: 151,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-25",
    source: "Bisnow LA",
    source_headline: "DJM advances Hollywood & Highland redevelopment",
    source_url: "https://bisnow.com/la/djm-hollywood",
    developer_track_record_score: 75,
    developer_active_projects: 5,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Stenn Parton",
    contact_title: "Chief Development Officer, DJM",
    contact_email: "sparton@djmcapital.com",
    origination_score: 73,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Stenn",
      "DJM Capital",
      "Hollywood & Highland Phase II",
      151,
      220,
      "Los Angeles",
      "The repositioning of Hollywood & Highland is one of the more interesting redevelopment stories in LA right now — interested in talking through how we could support the next phase.",
    ),
  },
  {
    project_name: "Pasadena Civic Tower",
    developer: "Greystar",
    city: "Los Angeles",
    submarket: "Pasadena",
    address: "180 S Lake Ave, Pasadena, CA",
    project_type: "Multifamily",
    units: 218,
    gsf: 252000,
    est_project_cost_m: 158,
    est_loan_need_m: 110,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-22",
    source: "LA Business Journal",
    source_headline: "Greystar receives permits for Pasadena tower",
    source_url: "https://labusinessjournal.com/greystar-pasadena",
    developer_track_record_score: 90,
    developer_active_projects: 35,
    prior_lender: "Existing relationship: Goldman Sachs",
    contact_name: "Wesley LeBlanc",
    contact_title: "Managing Director, Greystar Development",
    contact_email: "wleblanc@greystar.com",
    origination_score: 80,
    outreach_status: "Drafted",
    draft_email: draft(
      "Wesley",
      "Greystar",
      "Pasadena Civic Tower",
      110,
      218,
      "Los Angeles",
      "We've been wanting to expand our work with Greystar — Pasadena is a high-conviction submarket for us and the basis here looks compelling.",
    ),
  },
  {
    project_name: "The Westwood",
    developer: "Lincoln Property Company",
    city: "Los Angeles",
    submarket: "Westwood",
    address: "10920 Wilshire Blvd, Los Angeles, CA",
    project_type: "Multifamily",
    units: 178,
    gsf: 215000,
    est_project_cost_m: 132,
    est_loan_need_m: 92,
    approval_status: "Entitled",
    announcement_date: "2026-03-18",
    source: "Urbanize LA",
    source_headline: "Lincoln Property entitles 178-unit Westwood project",
    source_url: "https://urbanize.la/post/lincoln-westwood",
    developer_track_record_score: 85,
    developer_active_projects: 19,
    prior_lender: "Existing relationship: Wells Fargo",
    contact_name: "David Binswanger",
    contact_title: "EVP, Lincoln Property",
    contact_email: "dbinswanger@lpc.com",
    origination_score: 71,
    outreach_status: "Not Reached",
    draft_email: draft(
      "David",
      "Lincoln Property",
      "The Westwood",
      92,
      178,
      "Los Angeles",
      "Westwood multifamily near UCLA is some of the most resilient housing demand in LA — would be a great project to work together on.",
    ),
  },
  {
    project_name: "Long Beach Pine",
    developer: "Sares Regis Group",
    city: "Los Angeles",
    submarket: "Long Beach",
    address: "245 Pine Ave, Long Beach, CA",
    project_type: "Multifamily",
    units: 164,
    gsf: 198000,
    est_project_cost_m: 102,
    est_loan_need_m: 71,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-15",
    source: "Long Beach Business Journal",
    source_headline: "Sares Regis files for downtown Long Beach project",
    source_url: "https://lbbusinessjournal.com/sares-pine",
    developer_track_record_score: 79,
    developer_active_projects: 11,
    prior_lender: "First-time relationship",
    contact_name: "Geoffrey Stack",
    contact_title: "Senior MD, Sares Regis",
    contact_email: "gstack@sares-regis.com",
    origination_score: 70,
    outreach_status: "Drafted",
    draft_email: draft(
      "Geoffrey",
      "Sares Regis",
      "Long Beach Pine",
      71,
      164,
      "Los Angeles",
      "Long Beach multifamily fundamentals continue to outperform — happy to talk about how we'd structure a senior facility here.",
    ),
  },
  {
    project_name: "Beverly Hills Wilshire",
    developer: "Townscape Partners",
    city: "Los Angeles",
    submarket: "Beverly Hills",
    address: "9034 Wilshire Blvd, Beverly Hills, CA",
    project_type: "Condo",
    units: 84,
    gsf: 178000,
    est_project_cost_m: 198,
    est_loan_need_m: 138,
    approval_status: "Entitled",
    announcement_date: "2026-03-12",
    source: "The Real Deal LA",
    source_headline: "Townscape entitles luxury Beverly Hills condo",
    source_url: "https://therealdeal.com/la/townscape-bh",
    developer_track_record_score: 83,
    developer_active_projects: 4,
    prior_lender: "First-time relationship",
    contact_name: "Tyler Siegel",
    contact_title: "Principal, Townscape Partners",
    contact_email: "tsiegel@townscape.com",
    origination_score: 76,
    outreach_status: "Drafted",
    draft_email: draft(
      "Tyler",
      "Townscape",
      "Beverly Hills Wilshire",
      138,
      84,
      "Los Angeles",
      "Ultra-luxury BH condo with strong sponsor track record — exactly the kind of one-off, defensible product we like to lend on.",
    ),
  },
  {
    project_name: "Glendale Brand",
    developer: "AvalonBay Communities",
    city: "Los Angeles",
    submarket: "Glendale",
    address: "300 N Brand Blvd, Glendale, CA",
    project_type: "Multifamily",
    units: 295,
    gsf: 332000,
    est_project_cost_m: 188,
    est_loan_need_m: 132,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-08",
    source: "Urbanize LA",
    source_headline: "AvalonBay files 295-unit Glendale project",
    source_url: "https://urbanize.la/post/avalonbay-glendale",
    developer_track_record_score: 92,
    developer_active_projects: 28,
    prior_lender: "Public REIT — capital markets",
    contact_name: "Matthew Birenbaum",
    contact_title: "CIO, AvalonBay",
    contact_email: "mbirenbaum@avalonbay.com",
    origination_score: 65,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Matthew",
      "AvalonBay",
      "Glendale Brand",
      132,
      295,
      "Los Angeles",
      "Public REITs typically self-fund, but on construction we've seen some shifts in how AvalonBay is sourcing senior debt — happy to compare notes.",
    ),
  },
  {
    project_name: "Santa Monica Olympic",
    developer: "NMS Properties",
    city: "Los Angeles",
    submarket: "Santa Monica",
    address: "1430 Olympic Blvd, Santa Monica, CA",
    project_type: "Multifamily",
    units: 122,
    gsf: 152000,
    est_project_cost_m: 108,
    est_loan_need_m: 76,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-05",
    source: "Bisnow LA",
    source_headline: "NMS Properties advances Santa Monica project",
    source_url: "https://bisnow.com/la/nms-olympic",
    developer_track_record_score: 73,
    developer_active_projects: 6,
    prior_lender: "First-time relationship",
    contact_name: "Neil Shekhter",
    contact_title: "CEO, NMS Properties",
    contact_email: "nshekhter@nmsproperties.com",
    origination_score: 74,
    outreach_status: "Drafted",
    draft_email: draft(
      "Neil",
      "NMS",
      "Santa Monica Olympic",
      76,
      122,
      "Los Angeles",
      "Santa Monica multifamily basis is incredibly hard to put together — your site is a real one and we'd want to be in this story.",
    ),
  },
  {
    project_name: "K-Town Crown",
    developer: "Jamison Services",
    city: "Los Angeles",
    submarket: "Koreatown",
    address: "3680 Wilshire Blvd, Los Angeles, CA",
    project_type: "Office Conversion",
    units: 380,
    gsf: 425000,
    est_project_cost_m: 168,
    est_loan_need_m: 118,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-02",
    source: "The Real Deal LA",
    source_headline:
      "Jamison wins approval for office-to-resi K-Town conversion",
    source_url: "https://therealdeal.com/la/jamison-ktown",
    developer_track_record_score: 81,
    developer_active_projects: 16,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Jaime Lee",
    contact_title: "CEO, Jamison Realty",
    contact_email: "jlee@jamisonservices.com",
    origination_score: 86,
    outreach_status: "Drafted",
    draft_email: draft(
      "Jaime",
      "Jamison",
      "K-Town Crown",
      118,
      380,
      "Los Angeles",
      "Office-to-resi conversion is a thesis we have real conviction on — and Jamison is one of the only sponsors in LA with proven execution on these. Would love to be in the conversation on construction financing.",
    ),
  },
  {
    project_name: "West Hollywood Sunset",
    developer: "Faring",
    city: "Los Angeles",
    submarket: "West Hollywood",
    address: "8775 Sunset Blvd, West Hollywood, CA",
    project_type: "Hospitality",
    units: 195,
    gsf: 228000,
    est_project_cost_m: 178,
    est_loan_need_m: 125,
    approval_status: "Entitled",
    announcement_date: "2026-02-26",
    source: "Urbanize LA",
    source_headline: "Faring entitles 195-key WeHo lifestyle hotel",
    source_url: "https://urbanize.la/post/faring-sunset",
    developer_track_record_score: 77,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "Jason Illoulian",
    contact_title: "CEO, Faring",
    contact_email: "jilloulian@faring.com",
    origination_score: 72,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Jason",
      "Faring",
      "West Hollywood Sunset",
      125,
      195,
      "Los Angeles",
      "WeHo lifestyle hospitality is a high-conviction segment for us — Sunset corridor at 195 keys is a project we'd want to underwrite.",
    ),
  },
  {
    project_name: "DTLA Olive",
    developer: "Mitsui Fudosan America",
    city: "Los Angeles",
    submarket: "Downtown LA",
    address: "1212 S Olive St, Los Angeles, CA",
    project_type: "Multifamily",
    units: 412,
    gsf: 478000,
    est_project_cost_m: 268,
    est_loan_need_m: 188,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-02-22",
    source: "LA Business Journal",
    source_headline: "Mitsui Fudosan files 412-unit DTLA project",
    source_url: "https://labusinessjournal.com/mitsui-olive",
    developer_track_record_score: 86,
    developer_active_projects: 7,
    prior_lender: "First-time relationship",
    contact_name: "Sho Watanabe",
    contact_title: "President, Mitsui Fudosan America",
    contact_email: "swatanabe@mfamerica.com",
    origination_score: 78,
    outreach_status: "Drafted",
    draft_email: draft(
      "Sho",
      "Mitsui Fudosan",
      "DTLA Olive",
      188,
      412,
      "Los Angeles",
      "DTLA multifamily at this scale is hard to find — and Mitsui's institutional capital pairing well with senior construction debt is a story we'd be very interested in.",
    ),
  },
  {
    project_name: "Echo Park Reservoir",
    developer: "Property Development Centers",
    city: "Los Angeles",
    submarket: "Echo Park",
    address: "1730 Echo Park Ave, Los Angeles, CA",
    project_type: "Mixed-Use",
    units: 145,
    gsf: 192000,
    est_project_cost_m: 98,
    est_loan_need_m: 68,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-18",
    source: "Bisnow LA",
    source_headline: "PDC files Echo Park mixed-use development",
    source_url: "https://bisnow.com/la/pdc-echo-park",
    developer_track_record_score: 70,
    developer_active_projects: 3,
    prior_lender: "First-time relationship",
    contact_name: "Steve Mortensen",
    contact_title: "President, PDC",
    contact_email: "smortensen@pdc-la.com",
    origination_score: 64,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Steve",
      "PDC",
      "Echo Park Reservoir",
      68,
      145,
      "Los Angeles",
      "Echo Park mixed-use is a category we like — the right basis story would make this a clean construction loan for us.",
    ),
  },
  {
    project_name: "South Park Lofts",
    developer: "Trumark Companies",
    city: "Los Angeles",
    submarket: "South Park",
    address: "888 S Hope St, Los Angeles, CA",
    project_type: "Multifamily",
    units: 268,
    gsf: 312000,
    est_project_cost_m: 168,
    est_loan_need_m: 117,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-14",
    source: "Urbanize LA",
    source_headline: "Trumark advances South Park residential tower",
    source_url: "https://urbanize.la/post/trumark-south-park",
    developer_track_record_score: 72,
    developer_active_projects: 9,
    prior_lender: "Existing relationship: Comerica",
    contact_name: "Michael Maples",
    contact_title: "Managing Director, Trumark",
    contact_email: "mmaples@trumarkco.com",
    origination_score: 73,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Michael",
      "Trumark",
      "South Park Lofts",
      117,
      268,
      "Los Angeles",
      "South Park has compressed nicely in the last 18 months — happy to walk through what we're seeing on construction debt for projects of this profile.",
    ),
  },
  {
    project_name: "Inglewood Crenshaw",
    developer: "Watt Companies",
    city: "Los Angeles",
    submarket: "Inglewood",
    address: "3650 W Century Blvd, Inglewood, CA",
    project_type: "Multifamily",
    units: 312,
    gsf: 364000,
    est_project_cost_m: 168,
    est_loan_need_m: 118,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-02-10",
    source: "LA Business Journal",
    source_headline: "Watt Companies plans Inglewood multifamily near SoFi",
    source_url: "https://labusinessjournal.com/watt-inglewood",
    developer_track_record_score: 74,
    developer_active_projects: 7,
    prior_lender: "Existing relationship: Sumitomo",
    contact_name: "Nadine Watt",
    contact_title: "President, Watt Companies",
    contact_email: "nwatt@watt.com",
    origination_score: 75,
    outreach_status: "Drafted",
    draft_email: draft(
      "Nadine",
      "Watt",
      "Inglewood Crenshaw",
      118,
      312,
      "Los Angeles",
      "Inglewood near SoFi is one of the most under-discussed growth submarkets in LA — would love to put a senior construction facility together with Watt here.",
    ),
  },
  {
    project_name: "USC Figueroa",
    developer: "Magnolia Real Estate",
    city: "Los Angeles",
    submarket: "South LA",
    address: "3120 S Figueroa St, Los Angeles, CA",
    project_type: "Multifamily",
    units: 178,
    gsf: 196000,
    est_project_cost_m: 92,
    est_loan_need_m: 64,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-06",
    source: "The Real Deal LA",
    source_headline: "Magnolia files USC-adjacent student housing",
    source_url: "https://therealdeal.com/la/magnolia-usc",
    developer_track_record_score: 65,
    developer_active_projects: 4,
    prior_lender: "First-time relationship",
    contact_name: "Robert Kohorst",
    contact_title: "Principal, Magnolia",
    contact_email: "rkohorst@magnoliare.com",
    origination_score: 62,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Robert",
      "Magnolia",
      "USC Figueroa",
      64,
      178,
      "Los Angeles",
      "USC student-adjacent multifamily has had a strong run — interested in supporting a sponsor like Magnolia on the right structure.",
    ),
  },

  // ── MIAMI ──────────────────────────────────────────────────
  {
    project_name: "Brickell Reserve",
    developer: "Related Group",
    city: "Miami",
    submarket: "Brickell",
    address: "1428 Brickell Ave, Miami, FL",
    project_type: "Condo",
    units: 388,
    gsf: 612000,
    est_project_cost_m: 528,
    est_loan_need_m: 370,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-25",
    source: "The Real Deal Miami",
    source_headline: "Related secures permits for Brickell ultra-luxury tower",
    source_url: "https://therealdeal.com/miami/related-brickell-reserve",
    developer_track_record_score: 96,
    developer_active_projects: 18,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Jon Paul Pérez",
    contact_title: "President, Related Group",
    contact_email: "jpperez@relatedgroup.com",
    origination_score: 92,
    outreach_status: "Drafted",
    draft_email: draft(
      "Jon Paul",
      "Related Group",
      "Brickell Reserve",
      370,
      388,
      "Miami",
      "Related has been one of the most consistent operators in Brickell and a $370M senior construction facility is exactly the size of deal where we'd want to be your lead lender.",
    ),
  },
  {
    project_name: "Edgewater Bay Tower",
    developer: "Two Roads Development",
    city: "Miami",
    submarket: "Edgewater",
    address: "1900 N Bayshore Dr, Miami, FL",
    project_type: "Condo",
    units: 296,
    gsf: 442000,
    est_project_cost_m: 312,
    est_loan_need_m: 218,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-20",
    source: "South Florida Business Journal",
    source_headline: "Two Roads receives Edgewater tower permits",
    source_url: "https://bizjournals.com/southflorida/two-roads-edgewater",
    developer_track_record_score: 89,
    developer_active_projects: 6,
    prior_lender: "Existing relationship: City National",
    contact_name: "Reid Boren",
    contact_title: "Managing Partner, Two Roads",
    contact_email: "rboren@tworoadsdev.com",
    origination_score: 89,
    outreach_status: "Drafted",
    draft_email: draft(
      "Reid",
      "Two Roads",
      "Edgewater Bay Tower",
      218,
      296,
      "Miami",
      "Two Roads has been on a tear in Miami — Edgewater is exactly the submarket we want exposure to and this is a deal we'd want to lead.",
    ),
  },
  {
    project_name: "Wynwood Yards",
    developer: "Property Markets Group",
    city: "Miami",
    submarket: "Wynwood",
    address: "2600 NW 2nd Ave, Miami, FL",
    project_type: "Mixed-Use",
    units: 248,
    gsf: 358000,
    est_project_cost_m: 192,
    est_loan_need_m: 134,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-16",
    source: "The Real Deal Miami",
    source_headline: "PMG advances Wynwood Yards mixed-use",
    source_url: "https://therealdeal.com/miami/pmg-wynwood",
    developer_track_record_score: 88,
    developer_active_projects: 14,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Ryan Shear",
    contact_title: "Managing Partner, PMG",
    contact_email: "rshear@pmgmiami.com",
    origination_score: 84,
    outreach_status: "Drafted",
    draft_email: draft(
      "Ryan",
      "PMG",
      "Wynwood Yards",
      134,
      248,
      "Miami",
      "Wynwood mixed-use with PMG's track record — straight down the middle for what we'd want to back.",
    ),
  },
  {
    project_name: "Coral Gables Ponce",
    developer: "Mast Capital",
    city: "Miami",
    submarket: "Coral Gables",
    address: "2350 Ponce de Leon Blvd, Coral Gables, FL",
    project_type: "Multifamily",
    units: 218,
    gsf: 268000,
    est_project_cost_m: 158,
    est_loan_need_m: 110,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-13",
    source: "South Florida Business Journal",
    source_headline: "Mast Capital files for Coral Gables tower",
    source_url: "https://bizjournals.com/southflorida/mast-coral-gables",
    developer_track_record_score: 84,
    developer_active_projects: 9,
    prior_lender: "First-time relationship",
    contact_name: "Camilo Miguel Jr.",
    contact_title: "Founder & CEO, Mast Capital",
    contact_email: "cmiguel@mastcapital.com",
    origination_score: 81,
    outreach_status: "Drafted",
    draft_email: draft(
      "Camilo",
      "Mast Capital",
      "Coral Gables Ponce",
      110,
      218,
      "Miami",
      "Mast has been one of the most active and disciplined operators in South Florida — would love to start a lending relationship with you on Coral Gables.",
    ),
  },
  {
    project_name: "Aventura Gateway",
    developer: "13th Floor Investments",
    city: "Miami",
    submarket: "Aventura",
    address: "20801 Biscayne Blvd, Aventura, FL",
    project_type: "Mixed-Use",
    units: 312,
    gsf: 482000,
    est_project_cost_m: 248,
    est_loan_need_m: 174,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-09",
    source: "The Real Deal Miami",
    source_headline: "13th Floor breaks ground on Aventura Gateway",
    source_url: "https://therealdeal.com/miami/13th-floor-aventura",
    developer_track_record_score: 86,
    developer_active_projects: 11,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Arnaud Karsenti",
    contact_title: "Managing Principal, 13th Floor",
    contact_email: "akarsenti@13floor.com",
    origination_score: 85,
    outreach_status: "Drafted",
    draft_email: draft(
      "Arnaud",
      "13th Floor",
      "Aventura Gateway",
      174,
      312,
      "Miami",
      "Aventura mixed-use at this scale and 13th Floor's track record is a story we'd build a real lending relationship around.",
    ),
  },
  {
    project_name: "Coconut Grove Bayshore",
    developer: "Terra Group",
    city: "Miami",
    submarket: "Coconut Grove",
    address: "2800 Bayshore Dr, Miami, FL",
    project_type: "Condo",
    units: 142,
    gsf: 248000,
    est_project_cost_m: 198,
    est_loan_need_m: 138,
    approval_status: "Entitled",
    announcement_date: "2026-04-04",
    source: "South Florida Business Journal",
    source_headline: "Terra Group entitles Coconut Grove tower",
    source_url: "https://bizjournals.com/southflorida/terra-grove",
    developer_track_record_score: 91,
    developer_active_projects: 8,
    prior_lender: "Existing relationship: Goldman Sachs",
    contact_name: "David Martin",
    contact_title: "CEO, Terra",
    contact_email: "dmartin@terragroup.com",
    origination_score: 82,
    outreach_status: "Drafted",
    draft_email: draft(
      "David",
      "Terra",
      "Coconut Grove Bayshore",
      138,
      142,
      "Miami",
      "Coconut Grove waterfront condo at the level Terra builds — we'd want to be in this story on construction financing.",
    ),
  },
  {
    project_name: "Miami Worldcenter Phase III",
    developer: "Witkoff Group",
    city: "Miami",
    submarket: "Downtown Miami",
    address: "700 NE 1st Ave, Miami, FL",
    project_type: "Mixed-Use",
    units: 458,
    gsf: 712000,
    est_project_cost_m: 488,
    est_loan_need_m: 342,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-30",
    source: "The Real Deal Miami",
    source_headline: "Witkoff advances next phase of Miami Worldcenter",
    source_url: "https://therealdeal.com/miami/witkoff-mwc-3",
    developer_track_record_score: 93,
    developer_active_projects: 7,
    prior_lender: "Existing relationship: Apollo",
    contact_name: "Alex Witkoff",
    contact_title: "Co-CEO, Witkoff",
    contact_email: "awitkoff@witkoff.com",
    origination_score: 88,
    outreach_status: "Drafted",
    draft_email: draft(
      "Alex",
      "Witkoff",
      "Miami Worldcenter Phase III",
      342,
      458,
      "Miami",
      "Worldcenter is one of the most important large-scale projects in the country — happy to talk about how Madison could fit into the construction stack here.",
    ),
  },
  {
    project_name: "Miami Beach Collins",
    developer: "Crescent Heights",
    city: "Miami",
    submarket: "Miami Beach",
    address: "5800 Collins Ave, Miami Beach, FL",
    project_type: "Hospitality",
    units: 285,
    gsf: 412000,
    est_project_cost_m: 348,
    est_loan_need_m: 244,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-26",
    source: "South Florida Business Journal",
    source_headline: "Crescent Heights files 285-key Miami Beach hotel",
    source_url: "https://bizjournals.com/southflorida/crescent-collins",
    developer_track_record_score: 95,
    developer_active_projects: 9,
    prior_lender: "Existing relationship: JPMorgan",
    contact_name: "Sonny Kahn",
    contact_title: "Co-Founder, Crescent Heights",
    contact_email: "skahn@crescentheights.com",
    origination_score: 86,
    outreach_status: "Drafted",
    draft_email: draft(
      "Sonny",
      "Crescent Heights",
      "Miami Beach Collins",
      244,
      285,
      "Miami",
      "Miami Beach lifestyle hospitality of this caliber is a category where we have real conviction — let's talk about construction financing.",
    ),
  },
  {
    project_name: "Doral Lakes",
    developer: "Lennar Multifamily",
    city: "Miami",
    submarket: "Doral",
    address: "10500 NW 41st St, Doral, FL",
    project_type: "Multifamily",
    units: 348,
    gsf: 392000,
    est_project_cost_m: 178,
    est_loan_need_m: 124,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-20",
    source: "The Real Deal Miami",
    source_headline: "Lennar files 348-unit Doral project",
    source_url: "https://therealdeal.com/miami/lennar-doral",
    developer_track_record_score: 87,
    developer_active_projects: 22,
    prior_lender: "Public homebuilder — capital markets",
    contact_name: "Todd Farrell",
    contact_title: "President, LMV",
    contact_email: "tfarrell@lennar.com",
    origination_score: 70,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Todd",
      "Lennar",
      "Doral Lakes",
      124,
      348,
      "Miami",
      "LMV has been one of the most active multifamily builders in the country — interested in talking through how we approach senior construction facilities for portfolio sponsors.",
    ),
  },
  {
    project_name: "Midtown Miami N7",
    developer: "Magellan Development",
    city: "Miami",
    submarket: "Midtown",
    address: "3201 NE 1st Ave, Miami, FL",
    project_type: "Multifamily",
    units: 278,
    gsf: 318000,
    est_project_cost_m: 162,
    est_loan_need_m: 113,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-16",
    source: "South Florida Business Journal",
    source_headline: "Magellan advances Midtown Miami project",
    source_url: "https://bizjournals.com/southflorida/magellan-midtown",
    developer_track_record_score: 84,
    developer_active_projects: 6,
    prior_lender: "First-time relationship",
    contact_name: "David Carlins",
    contact_title: "President, Magellan",
    contact_email: "dcarlins@magellandevelopment.com",
    origination_score: 80,
    outreach_status: "Drafted",
    draft_email: draft(
      "David",
      "Magellan",
      "Midtown Miami N7",
      113,
      278,
      "Miami",
      "Midtown continues to deliver — and Magellan's product quality is well-respected. Let's discuss construction debt.",
    ),
  },
  {
    project_name: "Little Havana 22",
    developer: "Aria Development Group",
    city: "Miami",
    submarket: "Little Havana",
    address: "550 SW 22nd Ave, Miami, FL",
    project_type: "Multifamily",
    units: 188,
    gsf: 218000,
    est_project_cost_m: 102,
    est_loan_need_m: 71,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-11",
    source: "The Real Deal Miami",
    source_headline: "Aria advances Little Havana mid-rise",
    source_url: "https://therealdeal.com/miami/aria-havana",
    developer_track_record_score: 76,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "Tim Lobanov",
    contact_title: "Managing Director, Aria",
    contact_email: "tlobanov@ariadg.com",
    origination_score: 71,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Tim",
      "Aria",
      "Little Havana 22",
      71,
      188,
      "Miami",
      "Little Havana is one of the more underwriteable submarkets in Miami right now and Aria's product is well-positioned. Want to be in the conversation on construction debt.",
    ),
  },
  {
    project_name: "North Beach Towers",
    developer: "Fortune International Group",
    city: "Miami",
    submarket: "North Beach",
    address: "8701 Collins Ave, Miami Beach, FL",
    project_type: "Condo",
    units: 158,
    gsf: 268000,
    est_project_cost_m: 218,
    est_loan_need_m: 152,
    approval_status: "Entitled",
    announcement_date: "2026-03-06",
    source: "South Florida Business Journal",
    source_headline: "Fortune files North Beach luxury tower",
    source_url: "https://bizjournals.com/southflorida/fortune-north-beach",
    developer_track_record_score: 89,
    developer_active_projects: 7,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Edgardo Defortuna",
    contact_title: "President, Fortune International",
    contact_email: "edefortuna@fortuneintlgroup.com",
    origination_score: 79,
    outreach_status: "Drafted",
    draft_email: draft(
      "Edgardo",
      "Fortune International",
      "North Beach Towers",
      152,
      158,
      "Miami",
      "North Beach luxury condo with Fortune's resi-sales engine — exactly the profile of project we want to lend on.",
    ),
  },
  {
    project_name: "Brickell Key Phase II",
    developer: "Swire Properties",
    city: "Miami",
    submarket: "Brickell",
    address: "501 Brickell Key Dr, Miami, FL",
    project_type: "Mixed-Use",
    units: 412,
    gsf: 612000,
    est_project_cost_m: 412,
    est_loan_need_m: 288,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-01",
    source: "The Real Deal Miami",
    source_headline: "Swire files plans for Brickell Key expansion",
    source_url: "https://therealdeal.com/miami/swire-bk2",
    developer_track_record_score: 94,
    developer_active_projects: 5,
    prior_lender: "Public REIT — capital markets",
    contact_name: "Henry Bott",
    contact_title: "President, Swire Properties USA",
    contact_email: "hbott@swireproperties.com",
    origination_score: 75,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Henry",
      "Swire",
      "Brickell Key Phase II",
      288,
      412,
      "Miami",
      "Brickell Key expansion is one of the most consequential projects in Miami — happy to discuss where MRC could fit on senior construction.",
    ),
  },
  {
    project_name: "Allapattah Industrial",
    developer: "Robert Finvarb Companies",
    city: "Miami",
    submarket: "Allapattah",
    address: "2350 NW 17th Ave, Miami, FL",
    project_type: "Mixed-Use",
    units: 162,
    gsf: 192000,
    est_project_cost_m: 88,
    est_loan_need_m: 62,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-25",
    source: "South Florida Business Journal",
    source_headline: "Finvarb advances Allapattah mixed-use",
    source_url: "https://bizjournals.com/southflorida/finvarb-allapattah",
    developer_track_record_score: 71,
    developer_active_projects: 4,
    prior_lender: "First-time relationship",
    contact_name: "Robert Finvarb",
    contact_title: "Founder, Robert Finvarb Companies",
    contact_email: "rfinvarb@rfcompanies.com",
    origination_score: 65,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Robert",
      "Finvarb",
      "Allapattah Industrial",
      62,
      162,
      "Miami",
      "Allapattah is one of the more interesting basis stories in Miami — keen to talk through construction financing for projects of this profile.",
    ),
  },
  {
    project_name: "Bay Harbor Islands",
    developer: "Lndmrk Development",
    city: "Miami",
    submarket: "Bay Harbor Islands",
    address: "1100 Kane Concourse, Bay Harbor Islands, FL",
    project_type: "Condo",
    units: 92,
    gsf: 148000,
    est_project_cost_m: 122,
    est_loan_need_m: 85,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-19",
    source: "The Real Deal Miami",
    source_headline: "Lndmrk files Bay Harbor luxury condo",
    source_url: "https://therealdeal.com/miami/lndmrk-bay-harbor",
    developer_track_record_score: 78,
    developer_active_projects: 3,
    prior_lender: "First-time relationship",
    contact_name: "Sergio Pino",
    contact_title: "Founder, Lndmrk",
    contact_email: "spino@lndmrkdev.com",
    origination_score: 74,
    outreach_status: "Drafted",
    draft_email: draft(
      "Sergio",
      "Lndmrk",
      "Bay Harbor Islands",
      85,
      92,
      "Miami",
      "Bay Harbor luxury at this scale is a defensible product — would like to put a senior construction facility together with Lndmrk.",
    ),
  },
  {
    project_name: "Sunset Harbour",
    developer: "ROVR Development",
    city: "Miami",
    submarket: "Miami Beach",
    address: "1900 Bay Rd, Miami Beach, FL",
    project_type: "Mixed-Use",
    units: 134,
    gsf: 198000,
    est_project_cost_m: 142,
    est_loan_need_m: 99,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-02-13",
    source: "South Florida Business Journal",
    source_headline: "ROVR plans Sunset Harbour mixed-use",
    source_url: "https://bizjournals.com/southflorida/rovr-sunset",
    developer_track_record_score: 73,
    developer_active_projects: 4,
    prior_lender: "First-time relationship",
    contact_name: "Oscar Rodriguez",
    contact_title: "Founder, ROVR",
    contact_email: "orodriguez@rovrdev.com",
    origination_score: 72,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Oscar",
      "ROVR",
      "Sunset Harbour",
      99,
      134,
      "Miami",
      "Sunset Harbour basis is rare — interested in walking through construction financing for the project.",
    ),
  },

  // ── WEST PALM BEACH ────────────────────────────────────────
  {
    project_name: "Flagler Banyan",
    developer: "Related Companies",
    city: "West Palm Beach",
    submarket: "Downtown WPB",
    address: "350 S Flagler Dr, West Palm Beach, FL",
    project_type: "Mixed-Use",
    units: 285,
    gsf: 588000,
    est_project_cost_m: 412,
    est_loan_need_m: 288,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-23",
    source: "Palm Beach Daily News",
    source_headline: "Related Companies receives permits for Flagler tower",
    source_url: "https://palmbeachdailynews.com/related-flagler",
    developer_track_record_score: 97,
    developer_active_projects: 12,
    prior_lender: "Existing relationship: Bank of America",
    contact_name: "Stephen Ross",
    contact_title: "Founder & Chairman, Related",
    contact_email: "sross@related.com",
    origination_score: 93,
    outreach_status: "Drafted",
    draft_email: draft(
      "Stephen",
      "Related Companies",
      "Flagler Banyan",
      288,
      285,
      "West Palm Beach",
      "Related's transformation of WPB is one of the most compelling stories in real estate right now — a $288M senior construction facility on Flagler is a deal we'd want to lead.",
    ),
  },
  {
    project_name: "Northwood Village Lofts",
    developer: "NDT Development",
    city: "West Palm Beach",
    submarket: "Northwood",
    address: "415 Northwood Rd, West Palm Beach, FL",
    project_type: "Multifamily",
    units: 198,
    gsf: 232000,
    est_project_cost_m: 118,
    est_loan_need_m: 82,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-19",
    source: "South Florida Business Journal",
    source_headline: "NDT advances 198-unit Northwood project",
    source_url: "https://bizjournals.com/southflorida/ndt-northwood",
    developer_track_record_score: 80,
    developer_active_projects: 6,
    prior_lender: "First-time relationship",
    contact_name: "Ned Grace",
    contact_title: "Founder, NDT",
    contact_email: "ngrace@ndtdev.com",
    origination_score: 83,
    outreach_status: "Drafted",
    draft_email: draft(
      "Ned",
      "NDT",
      "Northwood Village Lofts",
      82,
      198,
      "West Palm Beach",
      "Northwood is one of the strongest emerging submarkets in WPB — interested in being your senior construction lender.",
    ),
  },
  {
    project_name: "El Cid Bayfront",
    developer: "Frisbie Group",
    city: "West Palm Beach",
    submarket: "El Cid",
    address: "2800 S Flagler Dr, West Palm Beach, FL",
    project_type: "Condo",
    units: 86,
    gsf: 168000,
    est_project_cost_m: 168,
    est_loan_need_m: 118,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-12",
    source: "Palm Beach Daily News",
    source_headline: "Frisbie advances ultra-luxury El Cid condo",
    source_url: "https://palmbeachdailynews.com/frisbie-elcid",
    developer_track_record_score: 88,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "Cody Crowell",
    contact_title: "Managing Partner, Frisbie",
    contact_email: "ccrowell@frisbiegroup.com",
    origination_score: 84,
    outreach_status: "Drafted",
    draft_email: draft(
      "Cody",
      "Frisbie",
      "El Cid Bayfront",
      118,
      86,
      "West Palm Beach",
      "Frisbie has been the most active sponsor in WPB luxury — would love to start a lending relationship on this project.",
    ),
  },
  {
    project_name: "CityPlace South",
    developer: "Affiliated Development",
    city: "West Palm Beach",
    submarket: "CityPlace",
    address: "550 Okeechobee Blvd, West Palm Beach, FL",
    project_type: "Multifamily",
    units: 256,
    gsf: 298000,
    est_project_cost_m: 158,
    est_loan_need_m: 110,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-07",
    source: "Palm Beach Post",
    source_headline: "Affiliated Development files CityPlace project",
    source_url: "https://palmbeachpost.com/affiliated-cityplace",
    developer_track_record_score: 76,
    developer_active_projects: 7,
    prior_lender: "First-time relationship",
    contact_name: "Jeff Burns",
    contact_title: "CEO, Affiliated Development",
    contact_email: "jburns@affdev.com",
    origination_score: 78,
    outreach_status: "Drafted",
    draft_email: draft(
      "Jeff",
      "Affiliated",
      "CityPlace South",
      110,
      256,
      "West Palm Beach",
      "CityPlace continues to be the strongest urban node in WPB — interested in talking construction debt with Affiliated.",
    ),
  },
  {
    project_name: "Clematis Lofts",
    developer: "Henni Holdings",
    city: "West Palm Beach",
    submarket: "Clematis",
    address: "200 Clematis St, West Palm Beach, FL",
    project_type: "Mixed-Use",
    units: 162,
    gsf: 218000,
    est_project_cost_m: 118,
    est_loan_need_m: 82,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-01",
    source: "South Florida Business Journal",
    source_headline: "Henni files Clematis mixed-use",
    source_url: "https://bizjournals.com/southflorida/henni-clematis",
    developer_track_record_score: 70,
    developer_active_projects: 3,
    prior_lender: "First-time relationship",
    contact_name: "Justin Ohayon",
    contact_title: "Principal, Henni Holdings",
    contact_email: "johayon@henniholdings.com",
    origination_score: 67,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Justin",
      "Henni",
      "Clematis Lofts",
      82,
      162,
      "West Palm Beach",
      "Clematis is heating up nicely — happy to discuss construction financing for the project.",
    ),
  },
  {
    project_name: "Palm Beach Lakes Tower",
    developer: "Kolter Group",
    city: "West Palm Beach",
    submarket: "Palm Beach Lakes",
    address: "2400 Palm Beach Lakes Blvd, West Palm Beach, FL",
    project_type: "Multifamily",
    units: 232,
    gsf: 268000,
    est_project_cost_m: 132,
    est_loan_need_m: 92,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-27",
    source: "Palm Beach Post",
    source_headline: "Kolter Group advances Palm Beach Lakes project",
    source_url: "https://palmbeachpost.com/kolter-pbl",
    developer_track_record_score: 83,
    developer_active_projects: 11,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Bobby Julien",
    contact_title: "CEO, Kolter Group",
    contact_email: "bjulien@kolter.com",
    origination_score: 76,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Bobby",
      "Kolter",
      "Palm Beach Lakes Tower",
      92,
      232,
      "West Palm Beach",
      "Kolter has been one of the most consistent operators in Florida — keen to talk about expanding our work together on construction debt.",
    ),
  },
  {
    project_name: "Currie Park Marina",
    developer: "BH3 Management",
    city: "West Palm Beach",
    submarket: "North End",
    address: "2400 N Flagler Dr, West Palm Beach, FL",
    project_type: "Mixed-Use",
    units: 318,
    gsf: 478000,
    est_project_cost_m: 268,
    est_loan_need_m: 188,
    approval_status: "Entitled",
    announcement_date: "2026-03-21",
    source: "Palm Beach Daily News",
    source_headline: "BH3 entitles Currie Park waterfront project",
    source_url: "https://palmbeachdailynews.com/bh3-currie-park",
    developer_track_record_score: 82,
    developer_active_projects: 6,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Daniel Lebensohn",
    contact_title: "Co-Founder, BH3",
    contact_email: "dlebensohn@bh3.com",
    origination_score: 81,
    outreach_status: "Drafted",
    draft_email: draft(
      "Daniel",
      "BH3",
      "Currie Park Marina",
      188,
      318,
      "West Palm Beach",
      "BH3's repositioning expertise paired with a Currie Park waterfront site — exactly the profile of project we want exposure to.",
    ),
  },
  {
    project_name: "Okeechobee Gateway",
    developer: "Driftwood Capital",
    city: "West Palm Beach",
    submarket: "Downtown WPB",
    address: "300 Okeechobee Blvd, West Palm Beach, FL",
    project_type: "Hospitality",
    units: 245,
    gsf: 312000,
    est_project_cost_m: 218,
    est_loan_need_m: 152,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-14",
    source: "South Florida Business Journal",
    source_headline: "Driftwood advances 245-key WPB hotel",
    source_url: "https://bizjournals.com/southflorida/driftwood-okeechobee",
    developer_track_record_score: 81,
    developer_active_projects: 8,
    prior_lender: "First-time relationship",
    contact_name: "Carlos Rodriguez Sr.",
    contact_title: "CEO, Driftwood Capital",
    contact_email: "crodriguez@driftwoodcapital.com",
    origination_score: 80,
    outreach_status: "Drafted",
    draft_email: draft(
      "Carlos",
      "Driftwood",
      "Okeechobee Gateway",
      152,
      245,
      "West Palm Beach",
      "WPB is finally getting the lifestyle hotel inventory it deserves — interested in being your senior construction lender on the project.",
    ),
  },
  {
    project_name: "South Olive Tower",
    developer: "Trinity Capital Advisors",
    city: "West Palm Beach",
    submarket: "South End",
    address: "2200 S Olive Ave, West Palm Beach, FL",
    project_type: "Multifamily",
    units: 145,
    gsf: 168000,
    est_project_cost_m: 92,
    est_loan_need_m: 64,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-09",
    source: "Palm Beach Post",
    source_headline: "Trinity Capital files South Olive project",
    source_url: "https://palmbeachpost.com/trinity-south-olive",
    developer_track_record_score: 75,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "Walker Collier",
    contact_title: "Managing Partner, Trinity Capital",
    contact_email: "wcollier@trinitycapital.com",
    origination_score: 67,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Walker",
      "Trinity Capital",
      "South Olive Tower",
      64,
      145,
      "West Palm Beach",
      "South End WPB has interesting basis dynamics — happy to talk through what construction debt could look like.",
    ),
  },
  {
    project_name: "Rosemary Square Phase IV",
    developer: "Related Companies",
    city: "West Palm Beach",
    submarket: "CityPlace",
    address: "700 S Rosemary Ave, West Palm Beach, FL",
    project_type: "Mixed-Use",
    units: 348,
    gsf: 528000,
    est_project_cost_m: 312,
    est_loan_need_m: 218,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-03",
    source: "Palm Beach Daily News",
    source_headline: "Related advances Rosemary Square next phase",
    source_url: "https://palmbeachdailynews.com/related-rosemary-4",
    developer_track_record_score: 97,
    developer_active_projects: 12,
    prior_lender: "Existing relationship: Bank of America",
    contact_name: "Gopal Rajegowda",
    contact_title: "SVP, Related",
    contact_email: "grajegowda@related.com",
    origination_score: 87,
    outreach_status: "Drafted",
    draft_email: draft(
      "Gopal",
      "Related",
      "Rosemary Square Phase IV",
      218,
      348,
      "West Palm Beach",
      "Rosemary Square is a category-defining project — we'd want to deepen our relationship with Related on the next phase.",
    ),
  },

  // ── SEATTLE ────────────────────────────────────────────────
  {
    project_name: "South Lake Union Block 3",
    developer: "Vulcan Real Estate",
    city: "Seattle",
    submarket: "South Lake Union",
    address: "1101 Westlake Ave N, Seattle, WA",
    project_type: "Multifamily",
    units: 412,
    gsf: 478000,
    est_project_cost_m: 268,
    est_loan_need_m: 188,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-24",
    source: "Puget Sound Business Journal",
    source_headline: "Vulcan files 412-unit SLU project",
    source_url: "https://bizjournals.com/seattle/vulcan-slu-3",
    developer_track_record_score: 96,
    developer_active_projects: 8,
    prior_lender: "Existing relationship: Wells Fargo",
    contact_name: "Lori Mason Curran",
    contact_title: "VP Real Estate, Vulcan",
    contact_email: "lmcurran@vulcan.com",
    origination_score: 90,
    outreach_status: "Drafted",
    draft_email: draft(
      "Lori",
      "Vulcan",
      "South Lake Union Block 3",
      188,
      412,
      "Seattle",
      "SLU multifamily of this scale with Vulcan as sponsor is exactly the kind of construction loan we want exposure to in Seattle right now.",
    ),
  },
  {
    project_name: "Belltown Skyline",
    developer: "Onni Group",
    city: "Seattle",
    submarket: "Belltown",
    address: "2300 First Ave, Seattle, WA",
    project_type: "Multifamily",
    units: 388,
    gsf: 442000,
    est_project_cost_m: 248,
    est_loan_need_m: 174,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-21",
    source: "The Urbanist",
    source_headline: "Onni Group secures Belltown tower permits",
    source_url: "https://theurbanist.org/onni-belltown",
    developer_track_record_score: 88,
    developer_active_projects: 11,
    prior_lender: "Existing relationship: Bank OZK",
    contact_name: "Chris Plummer",
    contact_title: "Director, Onni Seattle",
    contact_email: "cplummer@onni.com",
    origination_score: 88,
    outreach_status: "Drafted",
    draft_email: draft(
      "Chris",
      "Onni",
      "Belltown Skyline",
      174,
      388,
      "Seattle",
      "Belltown core tower — exactly where we'd want exposure on Seattle multifamily and Onni is a sponsor we'd want to do more with.",
    ),
  },
  {
    project_name: "Capitol Hill Pike",
    developer: "Holland Partner Group",
    city: "Seattle",
    submarket: "Capitol Hill",
    address: "1500 E Pike St, Seattle, WA",
    project_type: "Multifamily",
    units: 268,
    gsf: 312000,
    est_project_cost_m: 168,
    est_loan_need_m: 117,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-17",
    source: "Seattle Daily Journal of Commerce",
    source_headline: "Holland Partner files Capitol Hill project",
    source_url: "https://djc.com/holland-capitol-hill",
    developer_track_record_score: 85,
    developer_active_projects: 14,
    prior_lender: "Existing relationship: Wells Fargo",
    contact_name: "Trevor Vaughan",
    contact_title: "VP Development, Holland Partner",
    contact_email: "tvaughan@hollandpartnergroup.com",
    origination_score: 84,
    outreach_status: "Drafted",
    draft_email: draft(
      "Trevor",
      "Holland Partner",
      "Capitol Hill Pike",
      117,
      268,
      "Seattle",
      "Capitol Hill multifamily with Holland's track record is squarely in our sweet spot — let's discuss construction debt.",
    ),
  },
  {
    project_name: "Ballard Locks",
    developer: "Mack Urban",
    city: "Seattle",
    submarket: "Ballard",
    address: "5400 Ballard Ave NW, Seattle, WA",
    project_type: "Mixed-Use",
    units: 198,
    gsf: 248000,
    est_project_cost_m: 132,
    est_loan_need_m: 92,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-14",
    source: "The Urbanist",
    source_headline: "Mack Urban advances Ballard mixed-use",
    source_url: "https://theurbanist.org/mack-ballard",
    developer_track_record_score: 78,
    developer_active_projects: 6,
    prior_lender: "First-time relationship",
    contact_name: "Paul Keller",
    contact_title: "President, Mack Urban",
    contact_email: "pkeller@mackurban.com",
    origination_score: 76,
    outreach_status: "Drafted",
    draft_email: draft(
      "Paul",
      "Mack Urban",
      "Ballard Locks",
      92,
      198,
      "Seattle",
      "Ballard has been a remarkably steady performer — would love to start a lending relationship with Mack Urban here.",
    ),
  },
  {
    project_name: "First Hill Madison",
    developer: "Greystar",
    city: "Seattle",
    submarket: "First Hill",
    address: "1700 Madison St, Seattle, WA",
    project_type: "Multifamily",
    units: 245,
    gsf: 282000,
    est_project_cost_m: 158,
    est_loan_need_m: 110,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-11",
    source: "Puget Sound Business Journal",
    source_headline: "Greystar files First Hill project",
    source_url: "https://bizjournals.com/seattle/greystar-first-hill",
    developer_track_record_score: 90,
    developer_active_projects: 35,
    prior_lender: "Existing relationship: Goldman Sachs",
    contact_name: "Erik Mehr",
    contact_title: "MD, Greystar Pacific NW",
    contact_email: "emehr@greystar.com",
    origination_score: 81,
    outreach_status: "Drafted",
    draft_email: draft(
      "Erik",
      "Greystar",
      "First Hill Madison",
      110,
      245,
      "Seattle",
      "First Hill is medical-anchored demand on top of a clean basis — exactly what we'd want exposure to in Seattle.",
    ),
  },
  {
    project_name: "Pioneer Square Yesler",
    developer: "Daniels Real Estate",
    city: "Seattle",
    submarket: "Pioneer Square",
    address: "200 Yesler Way, Seattle, WA",
    project_type: "Office Conversion",
    units: 218,
    gsf: 312000,
    est_project_cost_m: 152,
    est_loan_need_m: 106,
    approval_status: "Permits Approved",
    announcement_date: "2026-04-06",
    source: "Seattle Daily Journal of Commerce",
    source_headline: "Daniels advances Yesler office-to-resi conversion",
    source_url: "https://djc.com/daniels-yesler",
    developer_track_record_score: 84,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "Kevin Daniels",
    contact_title: "President, Daniels Real Estate",
    contact_email: "kdaniels@danielsrealestate.com",
    origination_score: 88,
    outreach_status: "Drafted",
    draft_email: draft(
      "Kevin",
      "Daniels",
      "Pioneer Square Yesler",
      106,
      218,
      "Seattle",
      "Pioneer Square office-to-resi is exactly the conversion thesis we have conviction in. Daniels' track record on adaptive reuse here is unmatched.",
    ),
  },
  {
    project_name: "Queen Anne West",
    developer: "Continental Properties",
    city: "Seattle",
    submarket: "Queen Anne",
    address: "525 1st Ave W, Seattle, WA",
    project_type: "Multifamily",
    units: 188,
    gsf: 222000,
    est_project_cost_m: 122,
    est_loan_need_m: 85,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-04-03",
    source: "The Urbanist",
    source_headline: "Continental advances Queen Anne project",
    source_url: "https://theurbanist.org/continental-queen-anne",
    developer_track_record_score: 76,
    developer_active_projects: 7,
    prior_lender: "First-time relationship",
    contact_name: "Daniel Minahan",
    contact_title: "CEO, Continental Properties",
    contact_email: "dminahan@cproperties.com",
    origination_score: 73,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Daniel",
      "Continental",
      "Queen Anne West",
      85,
      188,
      "Seattle",
      "Queen Anne supply discipline has kept fundamentals strong — happy to be in the conversation on senior construction.",
    ),
  },
  {
    project_name: "U District Brooklyn",
    developer: "Lincoln Property Company",
    city: "Seattle",
    submarket: "U District",
    address: "4600 Brooklyn Ave NE, Seattle, WA",
    project_type: "Multifamily",
    units: 318,
    gsf: 358000,
    est_project_cost_m: 188,
    est_loan_need_m: 132,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-29",
    source: "Puget Sound Business Journal",
    source_headline: "Lincoln files 318-unit U District project",
    source_url: "https://bizjournals.com/seattle/lincoln-u-district",
    developer_track_record_score: 85,
    developer_active_projects: 19,
    prior_lender: "Existing relationship: Wells Fargo",
    contact_name: "Bryan Hill",
    contact_title: "Regional MD, Lincoln Property",
    contact_email: "bhill@lpc.com",
    origination_score: 83,
    outreach_status: "Drafted",
    draft_email: draft(
      "Bryan",
      "Lincoln Property",
      "U District Brooklyn",
      132,
      318,
      "Seattle",
      "U District has matured into a real institutional submarket — and a 318-unit Class A on Brooklyn is exactly the deal profile we want.",
    ),
  },
  {
    project_name: "Eastlake Fairview",
    developer: "Trinity Real Estate",
    city: "Seattle",
    submarket: "Eastlake",
    address: "2300 Fairview Ave E, Seattle, WA",
    project_type: "Multifamily",
    units: 162,
    gsf: 188000,
    est_project_cost_m: 102,
    est_loan_need_m: 71,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-24",
    source: "The Urbanist",
    source_headline: "Trinity files Eastlake project",
    source_url: "https://theurbanist.org/trinity-eastlake",
    developer_track_record_score: 70,
    developer_active_projects: 4,
    prior_lender: "First-time relationship",
    contact_name: "Jamie Davies",
    contact_title: "Principal, Trinity Real Estate",
    contact_email: "jdavies@trinityre.com",
    origination_score: 66,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Jamie",
      "Trinity",
      "Eastlake Fairview",
      71,
      162,
      "Seattle",
      "Eastlake's lake-front exposure with Trinity at the helm — interested in what construction debt could look like here.",
    ),
  },
  {
    project_name: "Beacon Hill Heights",
    developer: "Stream Real Estate",
    city: "Seattle",
    submarket: "Beacon Hill",
    address: "2700 Beacon Ave S, Seattle, WA",
    project_type: "Multifamily",
    units: 178,
    gsf: 198000,
    est_project_cost_m: 92,
    est_loan_need_m: 64,
    approval_status: "Permits Approved",
    announcement_date: "2026-03-19",
    source: "Seattle Daily Journal of Commerce",
    source_headline: "Stream files Beacon Hill project",
    source_url: "https://djc.com/stream-beacon-hill",
    developer_track_record_score: 73,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "John Schwartz",
    contact_title: "Founder, Stream Real Estate",
    contact_email: "jschwartz@streamre.com",
    origination_score: 70,
    outreach_status: "Not Reached",
    draft_email: draft(
      "John",
      "Stream",
      "Beacon Hill Heights",
      64,
      178,
      "Seattle",
      "Beacon Hill has been a basis story we like — happy to talk construction debt for the project.",
    ),
  },
  {
    project_name: "SLU Block 7",
    developer: "Touchstone Corporation",
    city: "Seattle",
    submarket: "South Lake Union",
    address: "1900 Boren Ave, Seattle, WA",
    project_type: "Mixed-Use",
    units: 358,
    gsf: 528000,
    est_project_cost_m: 312,
    est_loan_need_m: 218,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-13",
    source: "Puget Sound Business Journal",
    source_headline: "Touchstone advances SLU mixed-use",
    source_url: "https://bizjournals.com/seattle/touchstone-slu-7",
    developer_track_record_score: 87,
    developer_active_projects: 6,
    prior_lender: "Existing relationship: PNC",
    contact_name: "Doug Howe",
    contact_title: "Principal, Touchstone",
    contact_email: "dhowe@touchstonecorp.com",
    origination_score: 86,
    outreach_status: "Drafted",
    draft_email: draft(
      "Doug",
      "Touchstone",
      "SLU Block 7",
      218,
      358,
      "Seattle",
      "SLU mixed-use at this scale with Touchstone as sponsor — straight down the middle for what we'd want to lead.",
    ),
  },
  {
    project_name: "Belltown Battery",
    developer: "Bosa Development",
    city: "Seattle",
    submarket: "Belltown",
    address: "2200 Battery St, Seattle, WA",
    project_type: "Condo",
    units: 245,
    gsf: 372000,
    est_project_cost_m: 268,
    est_loan_need_m: 188,
    approval_status: "Entitled",
    announcement_date: "2026-03-07",
    source: "The Urbanist",
    source_headline: "Bosa Development entitles Belltown condo",
    source_url: "https://theurbanist.org/bosa-battery",
    developer_track_record_score: 89,
    developer_active_projects: 5,
    prior_lender: "First-time relationship",
    contact_name: "Nat Bosa",
    contact_title: "Founder, Bosa Development",
    contact_email: "nbosa@bosa.com",
    origination_score: 85,
    outreach_status: "Drafted",
    draft_email: draft(
      "Nat",
      "Bosa",
      "Belltown Battery",
      188,
      245,
      "Seattle",
      "Bosa's resi-condo execution is unmatched — would love to lead the construction facility on Belltown Battery.",
    ),
  },
  {
    project_name: "Madison Park Heights",
    developer: "Westbank",
    city: "Seattle",
    submarket: "Madison Park",
    address: "4200 E Madison St, Seattle, WA",
    project_type: "Mixed-Use",
    units: 195,
    gsf: 268000,
    est_project_cost_m: 192,
    est_loan_need_m: 134,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-03-04",
    source: "Seattle Daily Journal of Commerce",
    source_headline: "Westbank advances Madison Park project",
    source_url: "https://djc.com/westbank-madison-park",
    developer_track_record_score: 86,
    developer_active_projects: 7,
    prior_lender: "First-time relationship",
    contact_name: "Ian Gillespie",
    contact_title: "Founder, Westbank",
    contact_email: "igillespie@westbankcorp.com",
    origination_score: 80,
    outreach_status: "Drafted",
    draft_email: draft(
      "Ian",
      "Westbank",
      "Madison Park Heights",
      134,
      195,
      "Seattle",
      "Westbank's design-forward product is one-of-one and Madison Park is a defensible submarket — interested in being your senior construction lender.",
    ),
  },
  {
    project_name: "Northgate Mall Tower",
    developer: "Simon Property Group",
    city: "Seattle",
    submarket: "Northgate",
    address: "401 NE Northgate Way, Seattle, WA",
    project_type: "Mixed-Use",
    units: 412,
    gsf: 588000,
    est_project_cost_m: 312,
    est_loan_need_m: 218,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-28",
    source: "Puget Sound Business Journal",
    source_headline: "Simon advances Northgate redevelopment",
    source_url: "https://bizjournals.com/seattle/simon-northgate",
    developer_track_record_score: 88,
    developer_active_projects: 22,
    prior_lender: "Public REIT — capital markets",
    contact_name: "Mike McCarty",
    contact_title: "EVP Mixed-Use, Simon",
    contact_email: "mmccarty@simon.com",
    origination_score: 72,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Mike",
      "Simon",
      "Northgate Mall Tower",
      218,
      412,
      "Seattle",
      "Mall-redevelopment thesis is one we are spending a lot of time on — interested in talking about how Madison could fit.",
    ),
  },
  {
    project_name: "Fremont Aurora",
    developer: "Mortenson Development",
    city: "Seattle",
    submarket: "Fremont",
    address: "3700 Aurora Ave N, Seattle, WA",
    project_type: "Multifamily",
    units: 218,
    gsf: 248000,
    est_project_cost_m: 132,
    est_loan_need_m: 92,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-23",
    source: "The Urbanist",
    source_headline: "Mortenson files Fremont project",
    source_url: "https://theurbanist.org/mortenson-fremont",
    developer_track_record_score: 75,
    developer_active_projects: 8,
    prior_lender: "First-time relationship",
    contact_name: "Mark Mortenson",
    contact_title: "President, Mortenson Development",
    contact_email: "mmortenson@mortenson.com",
    origination_score: 75,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Mark",
      "Mortenson",
      "Fremont Aurora",
      92,
      218,
      "Seattle",
      "Fremont multifamily on Aurora is a strong basis story — would love to start a relationship on construction debt.",
    ),
  },
  {
    project_name: "International District Jackson",
    developer: "Uwajimaya / Lake Union Partners",
    city: "Seattle",
    submarket: "International District",
    address: "600 5th Ave S, Seattle, WA",
    project_type: "Mixed-Use",
    units: 158,
    gsf: 218000,
    est_project_cost_m: 122,
    est_loan_need_m: 85,
    approval_status: "Site Plan Approved",
    announcement_date: "2026-02-17",
    source: "Seattle Daily Journal of Commerce",
    source_headline: "Lake Union Partners files ID mixed-use",
    source_url: "https://djc.com/lup-id",
    developer_track_record_score: 71,
    developer_active_projects: 4,
    prior_lender: "First-time relationship",
    contact_name: "Patrick Foley",
    contact_title: "Principal, Lake Union Partners",
    contact_email: "pfoley@lakeunionpartners.com",
    origination_score: 67,
    outreach_status: "Not Reached",
    draft_email: draft(
      "Patrick",
      "Lake Union Partners",
      "International District Jackson",
      85,
      158,
      "Seattle",
      "ID mixed-use is an emerging story — happy to discuss construction financing.",
    ),
  },
  {
    project_name: "Roosevelt 65th",
    developer: "Security Properties",
    city: "Seattle",
    submarket: "Roosevelt",
    address: "1200 NE 65th St, Seattle, WA",
    project_type: "Multifamily",
    units: 192,
    gsf: 218000,
    est_project_cost_m: 118,
    est_loan_need_m: 82,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-11",
    source: "Puget Sound Business Journal",
    source_headline: "Security Properties files Roosevelt project",
    source_url: "https://bizjournals.com/seattle/security-roosevelt",
    developer_track_record_score: 80,
    developer_active_projects: 12,
    prior_lender: "Existing relationship: KeyBank",
    contact_name: "John Marasco",
    contact_title: "Managing Director, Security Properties",
    contact_email: "jmarasco@securityproperties.com",
    origination_score: 74,
    outreach_status: "Not Reached",
    draft_email: draft(
      "John",
      "Security Properties",
      "Roosevelt 65th",
      82,
      192,
      "Seattle",
      "Roosevelt has been one of the more interesting growth submarkets in north Seattle — keen to be in the construction debt conversation.",
    ),
  },
  {
    project_name: "Pike Pine Conversion",
    developer: "Hunters Capital",
    city: "Seattle",
    submarket: "Capitol Hill",
    address: "1000 E Pike St, Seattle, WA",
    project_type: "Office Conversion",
    units: 142,
    gsf: 188000,
    est_project_cost_m: 88,
    est_loan_need_m: 62,
    approval_status: "Permits Approved",
    announcement_date: "2026-02-05",
    source: "The Urbanist",
    source_headline: "Hunters Capital advances Pike-Pine office-to-resi",
    source_url: "https://theurbanist.org/hunters-pike-pine",
    developer_track_record_score: 72,
    developer_active_projects: 3,
    prior_lender: "First-time relationship",
    contact_name: "Michael Malone",
    contact_title: "Founder, Hunters Capital",
    contact_email: "mmalone@hunterscap.com",
    origination_score: 75,
    outreach_status: "Drafted",
    draft_email: draft(
      "Michael",
      "Hunters Capital",
      "Pike Pine Conversion",
      62,
      142,
      "Seattle",
      "Office-to-resi at Pike-Pine scale is squarely in our thesis — would love to be your construction lender on this.",
    ),
  },
];
