import Link from "next/link";
import { SignalMark } from "@/components/signal-mark";

export const metadata = {
  title: "Terms of Use · Dealwire",
  description: "The terms that govern your use of Dealwire.",
};

export default function TermsOfUsePage() {
  return (
    <div className="min-h-screen bg-[#080808] text-white font-sans">
      <nav className="relative z-50 px-6 lg:px-16 py-6 border-b border-white/[0.04]">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <SignalMark />
            <span className="text-base font-medium tracking-tight text-white/90">
              Dealwire
            </span>
          </Link>
          <Link
            href="/"
            className="text-sm text-white/60 hover:text-white transition-colors"
          >
            ← Back home
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 lg:px-16 py-16">
        <div className="mb-12">
          <h1 className="text-4xl font-semibold tracking-tight mb-3">
            Dealwire Terms of Use
          </h1>
          <p className="text-sm text-white/50 font-mono tracking-wide">
            Version 1.0 · Last revised: April 11, 2026
          </p>
        </div>

        <div className="space-y-8 text-white/75 leading-relaxed">
          <p>
            The website located at{" "}
            <a
              href="https://www.dealwire.ai/"
              className="text-[#C8A96E] hover:underline"
            >
              https://www.dealwire.ai/
            </a>{" "}
            (the &quot;Site&quot;) is a copyrighted work belonging to Frontstep
            AI, LLC, doing business as Dealwire (&quot;Company&quot;,
            &quot;us&quot;, &quot;our&quot;, and &quot;we&quot;). Certain
            features of the Site and Service may be subject to additional
            guidelines, terms, or rules, which will be posted on the Site in
            connection with such features. All such additional terms,
            guidelines, and rules are incorporated by reference into these
            Terms.
          </p>

          <div className="border-l-2 border-[#C8A96E] bg-white/[0.02] p-5 rounded">
            <p className="font-semibold text-white/90 uppercase text-sm tracking-wide">
              These Terms of Use (these &quot;Terms&quot;) set forth the legally
              binding terms and conditions that govern your use of the Site and
              Service. By accessing or using the Site or Service, you are
              accepting these Terms (on behalf of yourself or the entity that
              you represent), and you represent and warrant that you have the
              right, authority, and capacity to enter into these Terms. You may
              not access or use the Site or Service if you are not at least 18
              years old. If you do not agree with all of the provisions of these
              Terms, do not access and/or use the Site or Service.
            </p>
          </div>

          <div className="border-l-2 border-amber-500/60 bg-amber-500/[0.03] p-5 rounded">
            <p className="font-semibold text-white/90 uppercase text-sm tracking-wide">
              Please be aware that Section 10.2 contains provisions governing
              how to resolve disputes between you and Company. Among other
              things, Section 10.2 includes an agreement to arbitrate which
              requires, with limited exceptions, that all disputes between you
              and us shall be resolved by binding and final arbitration. Section
              10.2 also contains a class action and jury trial waiver. Please
              read Section 10.2 carefully.
            </p>
          </div>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              AI Output, Accuracy, and User Responsibility
            </h2>
            <p className="mb-3">
              Dealwire is an AI-powered platform for analyzing private market
              assets, including commercial real estate deals, businesses, and
              other investment opportunities. Our platform ingests deal
              materials (such as teasers and offering memorandums), enriches
              them with data from third-party sources and public records, and
              produces automated analyses, summaries, and recommendations.
            </p>
            <p className="mb-3">
              The outputs generated by Dealwire — including deal summaries,
              underwriting figures, property data, distress scores, go/no-go
              recommendations, and drafted communications — are{" "}
              <strong className="text-white">
                informational only and are not investment advice
              </strong>
              . We do not warrant or guarantee the accuracy, completeness, or
              reliability of any output. Third-party data sources may be
              incomplete, outdated, or incorrect, and AI-generated content may
              contain errors.
            </p>
            <p>
              You are solely responsible for any investment, underwriting, or
              business decision you make based on Dealwire&apos;s output. You
              agree to independently verify any material fact before acting on
              it and to comply with all applicable laws and regulations
              (including securities, fair housing, and anti-discrimination laws)
              in your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              1. Accounts
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  1.1 Account Creation.
                </h3>
                <p>
                  In order to use certain features of the Site, you must
                  register for an account (&quot;Account&quot;) and provide
                  certain information about yourself as prompted by the account
                  registration form. You represent and warrant that: (a) all
                  required registration information you submit is truthful and
                  accurate; and (b) you will maintain the accuracy of such
                  information. You may delete your Account at any time, for any
                  reason, by following the instructions on the Site. Company may
                  suspend or terminate your Account in accordance with Section
                  8.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  1.2 Account Responsibilities.
                </h3>
                <p>
                  You are responsible for maintaining the confidentiality of
                  your Account login information and are fully responsible for
                  all activities that occur under your Account, including any
                  actions taken by the agentic system on your behalf (such as
                  replies sent to brokers or counterparties). You agree to
                  immediately notify Company of any unauthorized use, or
                  suspected unauthorized use, of your Account or any other
                  breach of security. Company cannot and will not be liable for
                  any loss or damage arising from your failure to comply with
                  the above requirements.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              2. Access to the Site
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  2.1 License.
                </h3>
                <p>
                  Subject to these Terms, Company grants you a non-transferable,
                  non-exclusive, revocable, limited license to use and access
                  the Site and Service solely for your own internal business or
                  personal use.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  2.2 Certain Restrictions.
                </h3>
                <p>
                  The rights granted to you in these Terms are subject to the
                  following restrictions: (a) you shall not license, sell, rent,
                  lease, transfer, assign, distribute, host, or otherwise
                  commercially exploit the Site or Service, whether in whole or
                  in part, or any content displayed on the Site; (b) you shall
                  not modify, make derivative works of, disassemble, reverse
                  compile or reverse engineer any part of the Site or Service;
                  (c) you shall not access the Site or Service in order to build
                  a similar or competitive website, product, or service; and (d)
                  except as expressly stated herein, no part of the Site or
                  Service may be copied, reproduced, distributed, republished,
                  downloaded, displayed, posted or transmitted in any form or by
                  any means.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  2.3 Modification.
                </h3>
                <p>
                  Company reserves the right, at any time, to modify, suspend,
                  or discontinue the Site or Service (in whole or in part) with
                  or without notice to you. You agree that Company will not be
                  liable to you or to any third party for any modification,
                  suspension, or discontinuation of the Site or Service or any
                  part thereof.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  2.4 No Support or Maintenance.
                </h3>
                <p>
                  You acknowledge and agree that Company will have no obligation
                  to provide you with any support or maintenance in connection
                  with the Site or Service, except as expressly set forth in a
                  separate written agreement.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  2.5 Ownership.
                </h3>
                <p>
                  Excluding any User Content that you may provide (defined
                  below), you acknowledge that all intellectual property rights,
                  including copyrights, patents, trademarks, and trade secrets,
                  in the Site and its content are owned by Company or
                  Company&apos;s suppliers. Neither these Terms (nor your access
                  to the Site) transfers to you or any third party any rights,
                  title or interest in or to such intellectual property rights,
                  except for the limited access rights expressly set forth in
                  Section 2.1.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  2.6 Feedback.
                </h3>
                <p>
                  If you provide Company with any feedback or suggestions
                  regarding the Site or Service (&quot;Feedback&quot;), you
                  hereby assign to Company all rights in such Feedback and agree
                  that Company shall have the right to use and fully exploit
                  such Feedback and related information in any manner it deems
                  appropriate.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              3. User Content
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  3.1 User Content.
                </h3>
                <p>
                  &quot;User Content&quot; means any and all information and
                  content that a user submits to, or that is ingested by, the
                  Service — including deal materials, emails, offering
                  memorandums, underwriting inputs, investment criteria, and
                  other information provided through connected email accounts or
                  uploaded directly. You are solely responsible for your User
                  Content and for ensuring you have the right to submit it.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  3.2 License.
                </h3>
                <p>
                  You hereby grant (and you represent and warrant that you have
                  the right to grant) to Company a non-exclusive, royalty-free,
                  worldwide license to host, store, process, analyze, and
                  otherwise use your User Content solely as necessary to provide
                  the Service to you, to improve the Service, and as otherwise
                  permitted by our Privacy Policy.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  3.3 Acceptable Use Policy.
                </h3>
                <p className="mb-2">
                  The following terms constitute our &quot;Acceptable Use
                  Policy&quot;:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    You agree not to use the Site or Service to collect, upload,
                    transmit, display, or distribute any User Content that
                    violates any third-party right or is unlawful, harassing,
                    abusive, threatening, harmful, defamatory, false, or
                    otherwise objectionable.
                  </li>
                  <li>
                    You agree not to upload malware, send spam, harvest user
                    information, interfere with servers, attempt unauthorized
                    access, or use automated tools to scrape the Site.
                  </li>
                  <li>
                    You agree not to use the Service to make or influence
                    decisions in a manner that violates fair housing,
                    anti-discrimination, or equal credit opportunity laws.
                  </li>
                  <li>
                    You agree not to use the Service to send unsolicited
                    commercial communications in violation of CAN-SPAM or
                    similar laws.
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  3.4 Enforcement.
                </h3>
                <p>
                  We reserve the right (but have no obligation) to review,
                  refuse, and/or remove any User Content in our sole discretion,
                  and to investigate and/or take appropriate action against you
                  in our sole discretion if you violate the Acceptable Use
                  Policy.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              4. Indemnification
            </h2>
            <p>
              You agree to indemnify and hold Company (and its officers,
              employees, and agents) harmless, including costs and
              attorneys&apos; fees, from any claim or demand made by any third
              party due to or arising out of (a) your use of the Site or
              Service, (b) your violation of these Terms, (c) your violation of
              applicable laws or regulations, (d) your User Content, or (e) any
              investment or business decision you make based on Dealwire&apos;s
              output.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              5. Third-Party Links, Data, and Other Users
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  5.1 Third-Party Links and Data Sources.
                </h3>
                <p>
                  The Service integrates with and displays data from third-party
                  sources, including email providers (such as Microsoft
                  Outlook), public records (such as county and city data
                  portals), property data APIs, and other commercial data
                  providers. These third-party sources are not under the control
                  of Company, and Company is not responsible for the accuracy,
                  availability, or content of any third-party data or service.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  5.2 Release.
                </h3>
                <p>
                  You hereby release and forever discharge Company from, and
                  hereby waive and relinquish, each and every past, present, and
                  future dispute, claim, controversy, demand, right, obligation,
                  liability, action, and cause of action of every kind and
                  nature that has arisen or arises directly or indirectly out
                  of, or that relates directly or indirectly to, the Site or
                  Service.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              6. Disclaimers
            </h2>
            <div className="bg-white/[0.02] border border-white/5 p-5 rounded">
              <p className="font-semibold text-white/90 uppercase text-sm tracking-wide">
                The Site and Service are provided on an &quot;as-is&quot; and
                &quot;as available&quot; basis, and Company (and our suppliers)
                expressly disclaim any and all warranties and conditions of any
                kind, whether express, implied, or statutory, including all
                warranties or conditions of merchantability, fitness for a
                particular purpose, title, quiet enjoyment, accuracy, or
                non-infringement. Nothing in the Service constitutes investment,
                legal, tax, or accounting advice.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              7. Limitation on Liability
            </h2>
            <div className="bg-white/[0.02] border border-white/5 p-5 rounded space-y-3">
              <p className="font-semibold text-white/90 uppercase text-sm tracking-wide">
                To the maximum extent permitted by law, in no event shall
                Company (or our suppliers) be liable to you or any third party
                for any lost profits, lost data, costs of procurement of
                substitute products, or any indirect, consequential, exemplary,
                incidental, special, or punitive damages arising from or
                relating to these Terms or your use of, or inability to use, the
                Site or Service.
              </p>
              <p className="font-semibold text-white/90 uppercase text-sm tracking-wide">
                Notwithstanding anything to the contrary contained herein, our
                liability to you for any damages arising from or related to
                these Terms will at all times be limited to the greater of (a)
                the amounts paid by you to Company in the twelve months
                preceding the claim, or (b) one hundred U.S. dollars.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              8. Term and Termination
            </h2>
            <p>
              Subject to this Section, these Terms will remain in full force and
              effect while you use the Site or Service. We may suspend or
              terminate your rights to use the Site or Service (including your
              Account) at any time for any reason at our sole discretion,
              including for any use of the Site or Service in violation of these
              Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              9. Copyright Policy
            </h2>
            <p className="mb-4">
              Company respects the intellectual property of others and asks that
              users of our Site do the same. If you believe that your
              copyrighted work has been copied in a way that constitutes
              copyright infringement, please provide written notification to our
              designated Copyright Agent:
            </p>
            <div className="bg-white/[0.02] border border-white/5 p-5 rounded space-y-1 text-white/80">
              <p>
                <span className="text-white/60">Designated Agent:</span> Isaac
                Levine
              </p>
              <p>
                <span className="text-white/60">Address:</span> 23 Avondale
                Road, West Hartford, Connecticut 06117
              </p>
              <p>
                <span className="text-white/60">Email:</span>{" "}
                <a
                  href="mailto:isaac@dealwire.ai"
                  className="text-[#C8A96E] hover:underline"
                >
                  isaac@dealwire.ai
                </a>
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              10. General
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  10.1 Changes.
                </h3>
                <p>
                  These Terms are subject to occasional revision, and if we make
                  any substantial changes, we may notify you by sending you an
                  email to the last email address you provided to us (if any),
                  and/or by prominently posting notice of the changes on our
                  Site.
                </p>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  10.2 Dispute Resolution.
                </h3>
                <p className="font-medium text-white/90 mb-3">
                  Please read the following arbitration agreement carefully. It
                  requires you to arbitrate disputes with Company and limits the
                  manner in which you can seek relief.
                </p>
                <div className="ml-2 space-y-3">
                  <div>
                    <h4 className="font-medium text-white/90">
                      (a) Applicability of Arbitration Agreement.
                    </h4>
                    <p>
                      You agree that any dispute between you and any of the
                      Company parties relating in any way to the Site, Service,
                      or these Terms will be resolved by binding arbitration,
                      rather than in court, except for small claims court cases
                      and intellectual property disputes.
                    </p>
                  </div>
                  <div>
                    <h4 className="font-medium text-white/90">
                      (b) Informal Dispute Resolution.
                    </h4>
                    <p>
                      Before commencing arbitration, we will personally meet and
                      confer telephonically or via videoconference in a good
                      faith effort to resolve informally any dispute. Notice to
                      Company should be sent to:{" "}
                      <a
                        href="mailto:isaac@dealwire.ai"
                        className="text-[#C8A96E] hover:underline"
                      >
                        isaac@dealwire.ai
                      </a>
                      , or by mail to 23 Avondale Road, West Hartford,
                      Connecticut 06117.
                    </p>
                  </div>
                  <div>
                    <h4 className="font-medium text-white/90">
                      (c) Arbitration Rules and Forum.
                    </h4>
                    <p>
                      The arbitration will be conducted by JAMS. Unless you and
                      Company otherwise agree, the arbitration will be conducted
                      in the county where you reside.
                    </p>
                  </div>
                  <div>
                    <h4 className="font-medium text-white/90">
                      (d) Waiver of Jury Trial.
                    </h4>
                    <p className="font-semibold text-red-300">
                      You and the Company parties hereby waive any
                      constitutional and statutory rights to sue in court and
                      have a trial in front of a judge or a jury.
                    </p>
                  </div>
                  <div>
                    <h4 className="font-medium text-white/90">
                      (e) Waiver of Class or Other Non-Individualized Relief.
                    </h4>
                    <p className="font-semibold text-red-300">
                      You and Company agree that each of us may bring claims
                      against the other only on an individual basis and not on a
                      class, representative, or collective basis.
                    </p>
                  </div>
                  <div>
                    <h4 className="font-medium text-white/90">
                      (f) 30-Day Right to Opt Out.
                    </h4>
                    <p>
                      You have the right to opt out of the provisions of this
                      arbitration agreement by sending a timely written notice
                      within 30 days to: 23 Avondale Road, West Hartford,
                      Connecticut 06117, or email to{" "}
                      <a
                        href="mailto:isaac@dealwire.ai"
                        className="text-[#C8A96E] hover:underline"
                      >
                        isaac@dealwire.ai
                      </a>
                      .
                    </p>
                  </div>
                </div>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white/90 mb-2">
                  10.3 Contact Information.
                </h3>
                <div className="bg-white/[0.02] border border-white/5 p-5 rounded space-y-1 text-white/80">
                  <p className="font-semibold text-white">
                    Frontstep AI, LLC (d/b/a Dealwire)
                  </p>
                  <p>
                    <span className="text-white/60">Address:</span> 23 Avondale
                    Road, West Hartford, Connecticut 06117
                  </p>
                  <p>
                    <span className="text-white/60">Email:</span>{" "}
                    <a
                      href="mailto:isaac@dealwire.ai"
                      className="text-[#C8A96E] hover:underline"
                    >
                      isaac@dealwire.ai
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </section>

          <div className="border-t border-white/[0.06] pt-6 mt-12">
            <p className="text-xs font-mono text-white/30 tracking-wider">
              © {new Date().getFullYear()} · Frontstep AI, LLC. All rights
              reserved.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
